-- Telaris Pluriverse database schema (PostgreSQL).
--
-- GENERATED REFERENCE, not an installer. The Pluriverse builds and reconciles
-- its own schema at runtime via the idempotent db_ensure_*() helpers in
-- inc/db.php and inc/db_federation.php (called from inc/bootstrap.php on first
-- request); those helpers are the SOURCE OF TRUTH. This file is a faithful
-- snapshot of the live telaris_pluriverse schema for documentation, review, and
-- standing up a fresh database from SQL.
--
-- Regenerate with:
--   pg_dump --schema-only --no-owner --no-privileges --no-comments \
--     -h <host> -p 25060 -U telaris_pluriverse -d telaris_pluriverse
--   (sslmode=verify-ca, sslrootcert=/etc/ssl/polivoxia-pg1-ca.crt)
--
-- Covers the content tables (project_info, content_cache), the federation
-- registry + audit tables, and the self-service control plane (instance_requests,
-- provisioning_jobs, operator_bans, pluriverse_settings). Operator PII columns
-- are encrypted at rest (libsodium); the master key lives in secrets/, never here.

--
-- PostgreSQL database dump
--

\restrict e3UkoBaOgRw5RxnAP8efOzkGNYZy941MqoNXqDzVGrOlSrn1QYA4cBIIOo24OHY

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anomaly_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anomaly_log (
    id bigint NOT NULL,
    instance_id integer,
    anomaly_type character varying(64) NOT NULL,
    severity character varying(8) DEFAULT 'info'::character varying NOT NULL,
    details_summary character varying(1024),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT anomaly_log_severity_check CHECK (((severity)::text = ANY (ARRAY[('info'::character varying)::text, ('warning'::character varying)::text, ('severe'::character varying)::text])))
);


--
-- Name: anomaly_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anomaly_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anomaly_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blacklists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blacklists (
    id integer NOT NULL,
    entry_type character varying(16) NOT NULL,
    entry_value character varying(255) NOT NULL,
    reason text,
    added_by character varying(255),
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blacklists_entry_type_check CHECK (((entry_type)::text = ANY (ARRAY[('hostname'::character varying)::text, ('ip'::character varying)::text, ('domain'::character varying)::text])))
);


--
-- Name: blacklists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.blacklists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_cache (
    slug character varying(64) NOT NULL,
    locale character varying(8) NOT NULL,
    source_mtime bigint NOT NULL,
    rendered_html text NOT NULL,
    rendered_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: instance_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instance_requests (
    id integer NOT NULL,
    label character varying(63) NOT NULL,
    site_name character varying(255) NOT NULL,
    site_tagline character varying(512),
    editorial_framing text,
    locale character(2) DEFAULT 'en'::bpchar NOT NULL,
    federate boolean DEFAULT true NOT NULL,
    operator_name_enc bytea,
    operator_email_enc bytea NOT NULL,
    operator_email_lookup_hash bytea NOT NULL,
    request_ip_hash bytea,
    status character varying(20) DEFAULT 'pending_confirmation'::character varying NOT NULL,
    confirmed_at timestamp without time zone,
    reviewed_at timestamp without time zone,
    reviewed_by character varying(255),
    decision_reason text,
    instance_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT instance_requests_status_check CHECK (((status)::text = ANY ((ARRAY['pending_confirmation'::character varying, 'confirmed'::character varying, 'approved'::character varying, 'provisioning'::character varying, 'provisioned'::character varying, 'rejected'::character varying, 'failed'::character varying, 'banned'::character varying])::text[])))
);


--
-- Name: instance_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instance_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instance_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instance_status_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instance_status_log (
    id bigint NOT NULL,
    instance_id integer NOT NULL,
    actor character varying(255),
    action character varying(64) NOT NULL,
    details_summary character varying(1024),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: instance_status_log_archive; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instance_status_log_archive (
    id bigint NOT NULL,
    instance_id integer NOT NULL,
    actor character varying(255),
    action character varying(64) NOT NULL,
    details_summary character varying(1024),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: instance_status_log_archive_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instance_status_log_archive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instance_status_log_archive_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instance_status_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instance_status_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instance_status_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instances (
    id integer NOT NULL,
    hostname character varying(255) NOT NULL,
    url character varying(512) NOT NULL,
    pluriverse_endpoint character varying(512) NOT NULL,
    public_key bytea NOT NULL,
    previous_public_key bytea,
    key_rotated_at timestamp without time zone,
    rotation_reason character varying(16),
    operator_email_enc bytea NOT NULL,
    operator_email_lookup_hash bytea NOT NULL,
    other_contacts_enc bytea,
    pending_email_enc bytea,
    pending_email_lookup_hash bytea,
    pending_email_requested_at timestamp without time zone,
    label character varying(255) NOT NULL,
    editorial_framing text,
    publishable_slugs jsonb,
    bridges jsonb,
    locale character(2) DEFAULT 'en'::bpchar NOT NULL,
    is_highlighted boolean DEFAULT false NOT NULL,
    admission_status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    verify_by_at timestamp without time zone,
    last_seen_at timestamp without time zone,
    health_status character varying(16) DEFAULT 'unknown'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT instances_admission_status_check CHECK (((admission_status)::text = ANY (ARRAY[('pending'::character varying)::text, ('verified'::character varying)::text, ('published'::character varying)::text, ('rejected'::character varying)::text, ('blacklisted'::character varying)::text, ('outdated'::character varying)::text, ('withdrawn'::character varying)::text, ('revoked'::character varying)::text, ('expired'::character varying)::text]))),
    CONSTRAINT instances_health_status_check CHECK (((health_status)::text = ANY (ARRAY[('up'::character varying)::text, ('degraded'::character varying)::text, ('down'::character varying)::text, ('unknown'::character varying)::text]))),
    CONSTRAINT instances_rotation_reason_check CHECK (((rotation_reason IS NULL) OR ((rotation_reason)::text = ANY (ARRAY[('scheduled'::character varying)::text, ('operational'::character varying)::text, ('compromise'::character varying)::text]))))
);


--
-- Name: instances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: key_event_push_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.key_event_push_attempts (
    key_event_id bigint NOT NULL,
    instance_id integer NOT NULL,
    delivery_status character varying(16) DEFAULT 'pending'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp without time zone,
    next_attempt_at timestamp without time zone,
    last_error character varying(1024),
    CONSTRAINT key_event_push_attempts_delivery_status_check CHECK (((delivery_status)::text = ANY (ARRAY[('pending'::character varying)::text, ('delivered'::character varying)::text, ('failed'::character varying)::text, ('given_up'::character varying)::text])))
);


--
-- Name: key_events_signed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.key_events_signed (
    id bigint NOT NULL,
    origin_host character varying(255) NOT NULL,
    event_type character varying(24) NOT NULL,
    occurred_at timestamp without time zone NOT NULL,
    signed_payload text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT key_events_signed_event_type_check CHECK (((event_type)::text = ANY (ARRAY[('scheduled_rotation'::character varying)::text, ('operational_rotation'::character varying)::text, ('compromise'::character varying)::text, ('revocation'::character varying)::text])))
);


--
-- Name: key_events_signed_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.key_events_signed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.key_events_signed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: magic_link_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.magic_link_tokens (
    token_hash bytea NOT NULL,
    email_lookup_hash bytea NOT NULL,
    purpose character varying(16) DEFAULT 'operator'::character varying NOT NULL,
    instance_id integer,
    expires_at timestamp without time zone NOT NULL,
    consumed_at timestamp without time zone,
    CONSTRAINT magic_link_tokens_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['operator'::character varying, 'admin'::character varying, 'email-change'::character varying, 'request'::character varying])::text[])))
);


--
-- Name: operator_bans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operator_bans (
    id integer NOT NULL,
    operator_email_lookup_hash bytea NOT NULL,
    reason text,
    banned_by character varying(255),
    banned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: operator_bans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.operator_bans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operator_bans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pluriverse_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pluriverse_log (
    id bigint NOT NULL,
    event_type character varying(64) NOT NULL,
    actor character varying(255),
    target character varying(255),
    outcome character varying(8) NOT NULL,
    details_summary character varying(1024),
    ip_hash bytea,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pluriverse_log_outcome_check CHECK (((outcome)::text = ANY (ARRAY[('success'::character varying)::text, ('failure'::character varying)::text, ('warning'::character varying)::text])))
);


--
-- Name: pluriverse_log_archive; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pluriverse_log_archive (
    id bigint NOT NULL,
    event_type character varying(64) NOT NULL,
    actor character varying(255),
    target character varying(255),
    outcome character varying(8) NOT NULL,
    details_summary character varying(1024),
    ip_hash bytea,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pluriverse_log_outcome_check CHECK (((outcome)::text = ANY (ARRAY[('success'::character varying)::text, ('failure'::character varying)::text, ('warning'::character varying)::text])))
);


--
-- Name: pluriverse_log_archive_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pluriverse_log_archive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pluriverse_log_archive_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pluriverse_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pluriverse_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pluriverse_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pluriverse_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pluriverse_settings (
    key character varying(64) NOT NULL,
    value text NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: project_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_info (
    locale character varying(8) NOT NULL,
    html_lang text DEFAULT ''::text NOT NULL,
    title_suffix text DEFAULT ''::text NOT NULL,
    weaving text DEFAULT ''::text NOT NULL,
    tagline_desc text DEFAULT ''::text NOT NULL,
    nav_home text DEFAULT ''::text NOT NULL,
    nav_documentation text DEFAULT ''::text NOT NULL,
    nav_instances text DEFAULT ''::text NOT NULL,
    nav_manifest text DEFAULT ''::text NOT NULL,
    nav_changelog text DEFAULT ''::text NOT NULL,
    nav_source_code text DEFAULT ''::text NOT NULL,
    footer_status text DEFAULT ''::text NOT NULL,
    footer_privacy text DEFAULT ''::text NOT NULL,
    footer_terms text DEFAULT ''::text NOT NULL,
    doc_title text DEFAULT ''::text NOT NULL,
    doc_lead text DEFAULT ''::text NOT NULL,
    doc_download text DEFAULT ''::text NOT NULL,
    instance_title text DEFAULT ''::text NOT NULL,
    instance_lead text DEFAULT ''::text NOT NULL,
    changelog_title text DEFAULT ''::text NOT NULL,
    changelog_lead text DEFAULT ''::text NOT NULL,
    manifest_title text DEFAULT ''::text NOT NULL,
    manifest_lead text DEFAULT ''::text NOT NULL,
    manifest_download_pdf text DEFAULT ''::text NOT NULL,
    privacy_title text DEFAULT ''::text NOT NULL,
    privacy_lead text DEFAULT ''::text NOT NULL,
    privacy_download_pdf text DEFAULT ''::text NOT NULL,
    terms_title text DEFAULT ''::text NOT NULL,
    terms_lead text DEFAULT ''::text NOT NULL,
    terms_download_pdf text DEFAULT ''::text NOT NULL,
    verify_heading_verified text DEFAULT ''::text NOT NULL,
    verify_body_verified text DEFAULT ''::text NOT NULL,
    verify_heading_already_verified text DEFAULT ''::text NOT NULL,
    verify_body_already_verified text DEFAULT ''::text NOT NULL,
    verify_heading_expired text DEFAULT ''::text NOT NULL,
    verify_body_expired text DEFAULT ''::text NOT NULL,
    verify_heading_already_used text DEFAULT ''::text NOT NULL,
    verify_body_already_used text DEFAULT ''::text NOT NULL,
    verify_heading_invalid text DEFAULT ''::text NOT NULL,
    verify_body_invalid text DEFAULT ''::text NOT NULL,
    verify_heading_missing text DEFAULT ''::text NOT NULL,
    verify_body_missing text DEFAULT ''::text NOT NULL,
    verify_heading_instance_missing text DEFAULT ''::text NOT NULL,
    verify_body_instance_missing text DEFAULT ''::text NOT NULL,
    verify_heading_not_eligible text DEFAULT ''::text NOT NULL,
    verify_body_not_eligible text DEFAULT ''::text NOT NULL,
    verify_label_name text DEFAULT ''::text NOT NULL,
    verify_label_hostname text DEFAULT ''::text NOT NULL,
    verify_label_status text DEFAULT ''::text NOT NULL,
    verify_status_pending text DEFAULT ''::text NOT NULL,
    verify_status_verified text DEFAULT ''::text NOT NULL,
    verify_status_published text DEFAULT ''::text NOT NULL,
    verify_status_rejected text DEFAULT ''::text NOT NULL,
    verify_status_blacklisted text DEFAULT ''::text NOT NULL,
    verify_status_outdated text DEFAULT ''::text NOT NULL,
    verify_status_withdrawn text DEFAULT ''::text NOT NULL,
    verify_status_revoked text DEFAULT ''::text NOT NULL,
    verify_status_expired text DEFAULT ''::text NOT NULL,
    verify_back_home text DEFAULT ''::text NOT NULL,
    dashboard_title text DEFAULT ''::text NOT NULL,
    dashboard_lead text DEFAULT ''::text NOT NULL,
    dashboard_section_summary text DEFAULT ''::text NOT NULL,
    dashboard_label_name text DEFAULT ''::text NOT NULL,
    dashboard_label_url text DEFAULT ''::text NOT NULL,
    dashboard_label_hostname text DEFAULT ''::text NOT NULL,
    dashboard_label_status text DEFAULT ''::text NOT NULL,
    dashboard_label_locale text DEFAULT ''::text NOT NULL,
    dashboard_label_created text DEFAULT ''::text NOT NULL,
    dashboard_section_contacts text DEFAULT ''::text NOT NULL,
    dashboard_label_email text DEFAULT ''::text NOT NULL,
    dashboard_section_galaxies text DEFAULT ''::text NOT NULL,
    dashboard_galaxies_none text DEFAULT ''::text NOT NULL,
    dashboard_galaxies_count_fmt text DEFAULT ''::text NOT NULL,
    dashboard_galaxies_rescan_note text DEFAULT ''::text NOT NULL,
    dashboard_section_history text DEFAULT ''::text NOT NULL,
    dashboard_history_none text DEFAULT ''::text NOT NULL,
    dashboard_login_title text DEFAULT ''::text NOT NULL,
    dashboard_login_lead text DEFAULT ''::text NOT NULL,
    dashboard_login_sent text DEFAULT ''::text NOT NULL,
    dashboard_login_email_label text DEFAULT ''::text NOT NULL,
    dashboard_login_button text DEFAULT ''::text NOT NULL,
    dashboard_login_rate_limited text DEFAULT ''::text NOT NULL,
    dashboard_login_invalid_email text DEFAULT ''::text NOT NULL,
    dashboard_logout_button text DEFAULT ''::text NOT NULL,
    admin_title text DEFAULT ''::text NOT NULL,
    admin_lead_signed_in_as_fmt text DEFAULT ''::text NOT NULL,
    admin_section_instances text DEFAULT ''::text NOT NULL,
    admin_instances_none text DEFAULT ''::text NOT NULL,
    admin_instances_total_fmt text DEFAULT ''::text NOT NULL,
    admin_col_name text DEFAULT ''::text NOT NULL,
    admin_col_hostname text DEFAULT ''::text NOT NULL,
    admin_col_status text DEFAULT ''::text NOT NULL,
    admin_col_locale text DEFAULT ''::text NOT NULL,
    admin_col_created text DEFAULT ''::text NOT NULL,
    admin_actions_pending text DEFAULT ''::text NOT NULL,
    admin_login_title text DEFAULT ''::text NOT NULL,
    admin_login_lead text DEFAULT ''::text NOT NULL,
    admin_login_sent text DEFAULT ''::text NOT NULL,
    admin_login_email_label text DEFAULT ''::text NOT NULL,
    admin_login_button text DEFAULT ''::text NOT NULL,
    admin_login_rate_limited text DEFAULT ''::text NOT NULL,
    admin_login_invalid_email text DEFAULT ''::text NOT NULL,
    admin_col_actions text DEFAULT ''::text NOT NULL,
    admin_actions_help text DEFAULT ''::text NOT NULL,
    admin_btn_publish text DEFAULT ''::text NOT NULL,
    admin_btn_reject text DEFAULT ''::text NOT NULL,
    admin_btn_blacklist text DEFAULT ''::text NOT NULL,
    admin_btn_unpublish text DEFAULT ''::text NOT NULL,
    admin_btn_reinstate text DEFAULT ''::text NOT NULL,
    admin_confirm_action_fmt text DEFAULT ''::text NOT NULL,
    admin_flash_transition_ok_fmt text DEFAULT ''::text NOT NULL,
    admin_flash_csrf_err text DEFAULT ''::text NOT NULL,
    admin_flash_transition_err text DEFAULT ''::text NOT NULL,
    dashboard_section_withdraw text DEFAULT ''::text NOT NULL,
    dashboard_withdraw_help text DEFAULT ''::text NOT NULL,
    dashboard_withdraw_button text DEFAULT ''::text NOT NULL,
    dashboard_withdraw_confirm text DEFAULT ''::text NOT NULL,
    dashboard_withdraw_success text DEFAULT ''::text NOT NULL,
    dashboard_withdraw_error text DEFAULT ''::text NOT NULL,
    dashboard_section_edit text DEFAULT ''::text NOT NULL,
    dashboard_edit_help text DEFAULT ''::text NOT NULL,
    dashboard_edit_label_label text DEFAULT ''::text NOT NULL,
    dashboard_edit_framing_label text DEFAULT ''::text NOT NULL,
    dashboard_edit_framing_help text DEFAULT ''::text NOT NULL,
    dashboard_edit_locale_label text DEFAULT ''::text NOT NULL,
    dashboard_edit_save_button text DEFAULT ''::text NOT NULL,
    dashboard_edit_success text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_csrf text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_instance_missing text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_label_invalid text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_framing_too_long text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_locale_invalid text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_name_taken text DEFAULT ''::text NOT NULL,
    dashboard_edit_err_db text DEFAULT ''::text NOT NULL,
    dashboard_other_contacts_heading text DEFAULT ''::text NOT NULL,
    dashboard_other_contacts_help text DEFAULT ''::text NOT NULL,
    dashboard_contacts_service_placeholder text DEFAULT ''::text NOT NULL,
    dashboard_contacts_user_id_placeholder text DEFAULT ''::text NOT NULL,
    dashboard_contacts_add_button text DEFAULT ''::text NOT NULL,
    dashboard_contacts_remove_button text DEFAULT ''::text NOT NULL,
    dashboard_contacts_save_button text DEFAULT ''::text NOT NULL,
    dashboard_contacts_success text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_csrf text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_instance_missing text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_too_many text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_service_invalid text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_user_id_invalid text DEFAULT ''::text NOT NULL,
    dashboard_contacts_err_db text DEFAULT ''::text NOT NULL,
    dashboard_email_change_heading text DEFAULT ''::text NOT NULL,
    dashboard_email_change_help text DEFAULT ''::text NOT NULL,
    dashboard_email_change_new_label text DEFAULT ''::text NOT NULL,
    dashboard_email_change_new_placeholder text DEFAULT ''::text NOT NULL,
    dashboard_email_change_send_button text DEFAULT ''::text NOT NULL,
    dashboard_email_change_sent text DEFAULT ''::text NOT NULL,
    dashboard_email_change_pending_help text DEFAULT ''::text NOT NULL,
    dashboard_email_change_cancel_button text DEFAULT ''::text NOT NULL,
    dashboard_email_change_cancelled text DEFAULT ''::text NOT NULL,
    dashboard_email_change_confirmed text DEFAULT ''::text NOT NULL,
    dashboard_email_change_err_csrf text DEFAULT ''::text NOT NULL,
    dashboard_email_change_err_instance_missing text DEFAULT ''::text CONSTRAINT project_info_dashboard_email_change_err_instance_missi_not_null NOT NULL,
    dashboard_email_change_err_email_invalid text DEFAULT ''::text NOT NULL,
    dashboard_email_change_err_email_unchanged text DEFAULT ''::text CONSTRAINT project_info_dashboard_email_change_err_email_unchange_not_null NOT NULL,
    dashboard_email_change_err_email_taken text DEFAULT ''::text NOT NULL,
    dashboard_email_change_err_db text DEFAULT ''::text NOT NULL,
    footer_contact text DEFAULT ''::text NOT NULL,
    footer_governance text DEFAULT ''::text NOT NULL,
    contact_title text DEFAULT ''::text NOT NULL,
    contact_lead text DEFAULT ''::text NOT NULL,
    contact_section_repos_title text DEFAULT ''::text NOT NULL,
    contact_section_repos_body text DEFAULT ''::text NOT NULL,
    contact_section_admin_title text DEFAULT ''::text NOT NULL,
    contact_section_admin_body text DEFAULT ''::text NOT NULL,
    contact_section_security_title text DEFAULT ''::text NOT NULL,
    contact_section_security_body text DEFAULT ''::text NOT NULL,
    governance_title text DEFAULT ''::text NOT NULL,
    governance_lead text DEFAULT ''::text NOT NULL,
    governance_section_admission_title text DEFAULT ''::text NOT NULL,
    governance_section_admission_body text DEFAULT ''::text NOT NULL,
    governance_section_lifecycle_title text DEFAULT ''::text NOT NULL,
    governance_section_lifecycle_body text DEFAULT ''::text NOT NULL,
    governance_section_fork_title text DEFAULT ''::text NOT NULL,
    governance_section_fork_body text DEFAULT ''::text NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    footer_request text DEFAULT ''::text NOT NULL,
    instance_request_cta_title text DEFAULT ''::text NOT NULL,
    instance_request_cta_body text DEFAULT ''::text NOT NULL,
    instance_request_cta_button text DEFAULT ''::text NOT NULL,
    request_title text DEFAULT ''::text NOT NULL,
    request_lead text DEFAULT ''::text NOT NULL,
    request_closed_notice text DEFAULT ''::text NOT NULL,
    request_name_label text DEFAULT ''::text NOT NULL,
    request_name_ph text DEFAULT ''::text NOT NULL,
    request_email_label text DEFAULT ''::text NOT NULL,
    request_email_ph text DEFAULT ''::text NOT NULL,
    request_label_label text DEFAULT ''::text NOT NULL,
    request_label_help text DEFAULT ''::text NOT NULL,
    request_sitename_label text DEFAULT ''::text NOT NULL,
    request_sitename_ph text DEFAULT ''::text NOT NULL,
    request_tagline_label text DEFAULT ''::text NOT NULL,
    request_tagline_ph text DEFAULT ''::text NOT NULL,
    request_locale_label text DEFAULT ''::text NOT NULL,
    request_framing_label text DEFAULT ''::text NOT NULL,
    request_framing_help text DEFAULT ''::text NOT NULL,
    request_federate_label text DEFAULT ''::text NOT NULL,
    request_federate_help text DEFAULT ''::text NOT NULL,
    request_consent_html text DEFAULT ''::text NOT NULL,
    request_submit text DEFAULT ''::text NOT NULL,
    request_success_heading text DEFAULT ''::text NOT NULL,
    request_success_body text DEFAULT ''::text NOT NULL,
    request_err_email text DEFAULT ''::text NOT NULL,
    request_err_label_invalid text DEFAULT ''::text NOT NULL,
    request_err_label_taken text DEFAULT ''::text NOT NULL,
    request_err_sitename text DEFAULT ''::text NOT NULL,
    request_err_consent text DEFAULT ''::text NOT NULL,
    request_err_rate_limited text DEFAULT ''::text NOT NULL,
    request_err_generic text DEFAULT ''::text NOT NULL,
    request_confirm_heading_ok text DEFAULT ''::text NOT NULL,
    request_confirm_body_ok text DEFAULT ''::text NOT NULL,
    request_confirm_heading_already text DEFAULT ''::text NOT NULL,
    request_confirm_body_already text DEFAULT ''::text NOT NULL,
    request_confirm_heading_expired text DEFAULT ''::text NOT NULL,
    request_confirm_body_expired text DEFAULT ''::text NOT NULL,
    request_confirm_heading_invalid text DEFAULT ''::text NOT NULL,
    request_confirm_body_invalid text DEFAULT ''::text NOT NULL,
    admin_ss_title text DEFAULT ''::text NOT NULL,
    admin_ss_settings_title text DEFAULT ''::text NOT NULL,
    admin_ss_open_label text DEFAULT ''::text NOT NULL,
    admin_ss_cap_label text DEFAULT ''::text NOT NULL,
    admin_ss_save_button text DEFAULT ''::text NOT NULL,
    admin_ss_settings_saved text DEFAULT ''::text NOT NULL,
    admin_ss_requests_title text DEFAULT ''::text NOT NULL,
    admin_ss_requests_none text DEFAULT ''::text NOT NULL,
    admin_ss_col_operator text DEFAULT ''::text NOT NULL,
    admin_ss_col_label text DEFAULT ''::text NOT NULL,
    admin_ss_col_status text DEFAULT ''::text NOT NULL,
    admin_ss_col_created text DEFAULT ''::text NOT NULL,
    admin_ss_btn_approve text DEFAULT ''::text NOT NULL,
    admin_ss_btn_reject text DEFAULT ''::text NOT NULL,
    admin_ss_btn_ban text DEFAULT ''::text NOT NULL,
    admin_ss_btn_unban text DEFAULT ''::text NOT NULL,
    admin_ss_confirm_fmt text DEFAULT ''::text NOT NULL,
    admin_ss_flash_approved text DEFAULT ''::text NOT NULL,
    admin_ss_flash_rejected text DEFAULT ''::text NOT NULL,
    admin_ss_flash_banned text DEFAULT ''::text NOT NULL,
    admin_ss_flash_unbanned text DEFAULT ''::text NOT NULL,
    admin_ss_flash_err text DEFAULT ''::text NOT NULL,
    admin_ss_status_pending_confirmation text DEFAULT ''::text NOT NULL,
    admin_ss_status_confirmed text DEFAULT ''::text NOT NULL,
    admin_ss_status_approved text DEFAULT ''::text NOT NULL,
    admin_ss_status_provisioning text DEFAULT ''::text NOT NULL,
    admin_ss_status_provisioned text DEFAULT ''::text NOT NULL,
    admin_ss_status_rejected text DEFAULT ''::text NOT NULL,
    admin_ss_status_failed text DEFAULT ''::text NOT NULL,
    admin_ss_status_banned text DEFAULT ''::text NOT NULL,
    request_required_note text DEFAULT ''::text NOT NULL,
    request_err_name text DEFAULT ''::text NOT NULL,
    request_err_framing text DEFAULT ''::text NOT NULL,
    admin_ss_modal_title text DEFAULT ''::text NOT NULL,
    admin_ss_close text DEFAULT ''::text NOT NULL,
    admin_tab_federated text DEFAULT ''::text NOT NULL,
    admin_tab_orrery text DEFAULT ''::text NOT NULL,
    admin_ss_create_title text DEFAULT ''::text NOT NULL,
    admin_ss_create_help text DEFAULT ''::text NOT NULL,
    admin_ss_create_button text DEFAULT ''::text NOT NULL,
    admin_ss_flash_created text DEFAULT ''::text NOT NULL,
    admin_ss_instances_title text DEFAULT ''::text NOT NULL,
    admin_ss_instances_none text DEFAULT ''::text NOT NULL
);


--
-- Name: provisioning_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provisioning_jobs (
    id bigint NOT NULL,
    request_id integer,
    job_type character varying(16) DEFAULT 'provision'::character varying NOT NULL,
    label character varying(63) NOT NULL,
    payload jsonb,
    status character varying(16) DEFAULT 'queued'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp without time zone,
    next_attempt_at timestamp without time zone,
    last_error character varying(2048),
    result jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT provisioning_jobs_job_type_check CHECK (((job_type)::text = ANY ((ARRAY['provision'::character varying, 'deprovision'::character varying, 'suspend'::character varying, 'resume'::character varying])::text[]))),
    CONSTRAINT provisioning_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying, 'done'::character varying, 'failed'::character varying, 'given_up'::character varying])::text[])))
);


--
-- Name: provisioning_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provisioning_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provisioning_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registry_admins (
    id integer NOT NULL,
    email_enc bytea NOT NULL,
    email_lookup_hash bytea NOT NULL,
    display_name character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    seeded_via character varying(8) DEFAULT 'web'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT registry_admins_seeded_via_check CHECK (((seeded_via)::text = ANY (ARRAY[('cli'::character varying)::text, ('web'::character varying)::text])))
);


--
-- Name: registry_admins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registry_admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    session_id bytea NOT NULL,
    subject_type character varying(20) NOT NULL,
    subject_id integer NOT NULL,
    csrf_token bytea,
    chooser_email_hash bytea,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_activity_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    CONSTRAINT sessions_subject_type_check CHECK (((subject_type)::text = ANY (ARRAY[('operator'::character varying)::text, ('admin'::character varying)::text, ('operator-chooser'::character varying)::text])))
);


--
-- Name: anomaly_log anomaly_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anomaly_log
    ADD CONSTRAINT anomaly_log_pkey PRIMARY KEY (id);


--
-- Name: blacklists blacklists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blacklists
    ADD CONSTRAINT blacklists_pkey PRIMARY KEY (id);


--
-- Name: content_cache content_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_cache
    ADD CONSTRAINT content_cache_pkey PRIMARY KEY (slug, locale);


--
-- Name: instance_requests instance_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_requests
    ADD CONSTRAINT instance_requests_pkey PRIMARY KEY (id);


--
-- Name: instance_status_log_archive instance_status_log_archive_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_status_log_archive
    ADD CONSTRAINT instance_status_log_archive_pkey PRIMARY KEY (id);


--
-- Name: instance_status_log instance_status_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_status_log
    ADD CONSTRAINT instance_status_log_pkey PRIMARY KEY (id);


--
-- Name: instances instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instances
    ADD CONSTRAINT instances_pkey PRIMARY KEY (id);


--
-- Name: key_event_push_attempts key_event_push_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_event_push_attempts
    ADD CONSTRAINT key_event_push_attempts_pkey PRIMARY KEY (key_event_id, instance_id);


--
-- Name: key_events_signed key_events_signed_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_events_signed
    ADD CONSTRAINT key_events_signed_pkey PRIMARY KEY (id);


--
-- Name: magic_link_tokens magic_link_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.magic_link_tokens
    ADD CONSTRAINT magic_link_tokens_pkey PRIMARY KEY (token_hash);


--
-- Name: operator_bans operator_bans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_bans
    ADD CONSTRAINT operator_bans_pkey PRIMARY KEY (id);


--
-- Name: pluriverse_log_archive pluriverse_log_archive_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pluriverse_log_archive
    ADD CONSTRAINT pluriverse_log_archive_pkey PRIMARY KEY (id);


--
-- Name: pluriverse_log pluriverse_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pluriverse_log
    ADD CONSTRAINT pluriverse_log_pkey PRIMARY KEY (id);


--
-- Name: pluriverse_settings pluriverse_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pluriverse_settings
    ADD CONSTRAINT pluriverse_settings_pkey PRIMARY KEY (key);


--
-- Name: project_info project_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_info
    ADD CONSTRAINT project_info_pkey PRIMARY KEY (locale);


--
-- Name: provisioning_jobs provisioning_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provisioning_jobs
    ADD CONSTRAINT provisioning_jobs_pkey PRIMARY KEY (id);


--
-- Name: registry_admins registry_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registry_admins
    ADD CONSTRAINT registry_admins_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (session_id);


--
-- Name: operator_bans uniq_ban_lookup; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_bans
    ADD CONSTRAINT uniq_ban_lookup UNIQUE (operator_email_lookup_hash);


--
-- Name: registry_admins uniq_email_lookup; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registry_admins
    ADD CONSTRAINT uniq_email_lookup UNIQUE (email_lookup_hash);


--
-- Name: instances uniq_hostname; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instances
    ADD CONSTRAINT uniq_hostname UNIQUE (hostname);


--
-- Name: instances uniq_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instances
    ADD CONSTRAINT uniq_label UNIQUE (label);


--
-- Name: blacklists uniq_type_value; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blacklists
    ADD CONSTRAINT uniq_type_value UNIQUE (entry_type, entry_value);


--
-- Name: idx_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_actor ON public.pluriverse_log USING btree (actor, created_at);


--
-- Name: idx_anomaly_instance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_anomaly_instance ON public.anomaly_log USING btree (instance_id);


--
-- Name: idx_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_created ON public.key_events_signed USING btree (created_at);


--
-- Name: idx_email_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_expires ON public.magic_link_tokens USING btree (email_lookup_hash, expires_at);


--
-- Name: idx_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_type ON public.pluriverse_log USING btree (event_type, created_at);


--
-- Name: idx_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expires ON public.sessions USING btree (expires_at);


--
-- Name: idx_instance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instance ON public.instance_status_log USING btree (instance_id, created_at);


--
-- Name: idx_ir_instance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ir_instance ON public.instance_requests USING btree (instance_id);


--
-- Name: idx_ir_label; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ir_label ON public.instance_requests USING btree (label);


--
-- Name: idx_ir_operator_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ir_operator_lookup ON public.instance_requests USING btree (operator_email_lookup_hash);


--
-- Name: idx_ir_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ir_status ON public.instance_requests USING btree (status, created_at);


--
-- Name: idx_kepa_instance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kepa_instance ON public.key_event_push_attempts USING btree (instance_id);


--
-- Name: idx_operator_email_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_operator_email_lookup ON public.instances USING btree (operator_email_lookup_hash);


--
-- Name: idx_origin_occurred; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_origin_occurred ON public.key_events_signed USING btree (origin_host, occurred_at);


--
-- Name: idx_pending_email_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pending_email_lookup ON public.instances USING btree (pending_email_lookup_hash);


--
-- Name: idx_pending_next; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pending_next ON public.key_event_push_attempts USING btree (delivery_status, next_attempt_at);


--
-- Name: idx_pj_claim; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pj_claim ON public.provisioning_jobs USING btree (status, next_attempt_at);


--
-- Name: idx_pj_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pj_request ON public.provisioning_jobs USING btree (request_id);


--
-- Name: idx_rendered_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rendered_at ON public.content_cache USING btree (rendered_at);


--
-- Name: idx_severity_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_severity_created ON public.anomaly_log USING btree (severity, created_at);


--
-- Name: idx_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_subject ON public.sessions USING btree (subject_type, subject_id);


--
-- Name: instance_status_log_archive_instance_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX instance_status_log_archive_instance_id_created_at_idx ON public.instance_status_log_archive USING btree (instance_id, created_at);


--
-- Name: pluriverse_log_archive_actor_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pluriverse_log_archive_actor_created_at_idx ON public.pluriverse_log_archive USING btree (actor, created_at);


--
-- Name: pluriverse_log_archive_event_type_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pluriverse_log_archive_event_type_created_at_idx ON public.pluriverse_log_archive USING btree (event_type, created_at);


--
-- Name: instance_requests trg_instance_requests_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_instance_requests_updated_at BEFORE UPDATE ON public.instance_requests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: instances trg_instances_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_instances_updated_at BEFORE UPDATE ON public.instances FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: project_info trg_project_info_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_project_info_updated_at BEFORE UPDATE ON public.project_info FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: provisioning_jobs trg_provisioning_jobs_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_provisioning_jobs_updated_at BEFORE UPDATE ON public.provisioning_jobs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: anomaly_log anomaly_log_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anomaly_log
    ADD CONSTRAINT anomaly_log_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON DELETE SET NULL;


--
-- Name: instance_requests instance_requests_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_requests
    ADD CONSTRAINT instance_requests_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON DELETE SET NULL;


--
-- Name: instance_status_log instance_status_log_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_status_log
    ADD CONSTRAINT instance_status_log_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON DELETE CASCADE;


--
-- Name: key_event_push_attempts key_event_push_attempts_instance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_event_push_attempts
    ADD CONSTRAINT key_event_push_attempts_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id) ON DELETE CASCADE;


--
-- Name: key_event_push_attempts key_event_push_attempts_key_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_event_push_attempts
    ADD CONSTRAINT key_event_push_attempts_key_event_id_fkey FOREIGN KEY (key_event_id) REFERENCES public.key_events_signed(id) ON DELETE CASCADE;


--
-- Name: provisioning_jobs provisioning_jobs_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provisioning_jobs
    ADD CONSTRAINT provisioning_jobs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.instance_requests(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict e3UkoBaOgRw5RxnAP8efOzkGNYZy941MqoNXqDzVGrOlSrn1QYA4cBIIOo24OHY

