<?php
declare(strict_types=1);

/**
 * Default project_info chrome strings, one row per locale.
 *
 * Used by db_seed_project_info() to populate missing locale rows. Existing
 * rows are never overwritten — operators may edit the table directly.
 *
 * Translation policy: ES tú-form, PT você-form, FR tu-form. Gender-neutral
 * across all locales. See [[feedback-telaris-translation-style]] for canon.
 *
 * Lifted from /var/www/www.telaris.ca/build.py I18N dict (which the PHP
 * migration replaces). When this list and that one drift, this file wins
 * once the PHP migration ships; build.py will be removed at cutover.
 */

function pluriverse_project_info_defaults(): array {
    return [
        'en' => [
            'html_lang' => 'en',
            'title_suffix' => 'Telaris',
            'weaving' => 'weaving memory',
            'tagline_desc' => 'A decolonial knowledge archive project. Relational, P2P, non-hierarchical. Threaded by meaning.',
            'nav_home' => 'Home',
            'nav_documentation' => 'Documentation',
            'nav_instances' => 'Instances',
            'nav_manifest' => 'Manifest',
            'nav_source_code' => 'Source code',
            'footer_status' => 'System: Online',
            'footer_privacy' => 'Privacy',
            'footer_terms' => 'Terms',
            'doc_title' => 'Documentation',
            'doc_lead' => 'Telaris documentation, available as downloadable PDFs. Each document is also available in Spanish, Portuguese, and French; use the language toggle in the navigation bar to switch.',
            'doc_download' => 'Download PDF',
            'instance_title' => 'Active instances',
            'instance_lead' => 'Telaris is run by independent operators. Each instance is governed by the operator who runs it and the editors and source communities who contribute to it. Below are the instances currently active.',
            'manifest_title' => 'Manifest',
            'manifest_lead' => 'A statement of position, kept short on purpose. What Telaris is, what it refuses, and the six principles that hold it together.',
            'manifest_download_pdf' => 'Download as PDF',
            'privacy_title' => 'Privacy',
            'privacy_lead' => 'How Telaris handles data, at www.telaris.ca and across the network of independent instances.',
            'privacy_download_pdf' => 'Download as PDF',
            'terms_title' => 'Terms of Use',
            'terms_lead' => 'How the website at www.telaris.ca and the Telaris software are offered to visitors, operators, and editors.',
            'terms_download_pdf' => 'Download as PDF',
            'verify_heading_verified' => 'Email confirmed',
            'verify_body_verified' => 'Your join request is now verified. An admin will review your instance and let you know by email when it is published in the Pluriverse.',
            'verify_heading_already_verified' => 'Already confirmed',
            'verify_body_already_verified' => 'Your join request was already verified. You will receive an email when an admin reviews your instance.',
            'verify_heading_expired' => 'Link expired',
            'verify_body_expired' => "This verification link has expired. You can submit a new join request from your Telaris instance's admin panel.",
            'verify_heading_already_used' => 'Link already used',
            'verify_body_already_used' => 'This verification link has already been used. If your instance is not yet verified, submit a new join request from the admin panel.',
            'verify_heading_invalid' => 'Link not valid',
            'verify_body_invalid' => 'This verification link is not valid. Check that you opened the most recent email, or submit a new join request from the admin panel.',
            'verify_heading_missing' => 'No token in URL',
            'verify_body_missing' => 'This page expects a one-time verification token. Open the link from the email you received after submitting your join request.',
            'verify_heading_instance_missing' => 'Instance not found',
            'verify_body_instance_missing' => 'Your join request was verified, but the associated instance could not be located. Contact an admin if this is unexpected.',
            'verify_label_name' => 'Name',
            'verify_label_hostname' => 'Hostname',
            'verify_label_status' => 'Status',
            'verify_status_pending' => 'pending',
            'verify_status_verified' => 'verified',
            'verify_status_published' => 'published',
            'verify_status_rejected' => 'rejected',
            'verify_status_blacklisted' => 'blacklisted',
            'verify_status_outdated' => 'outdated',
            'verify_status_withdrawn' => 'withdrawn',
            'verify_status_revoked' => 'revoked',
            'verify_back_home' => 'Back to the Pluriverse',
        ],
        'es' => [
            'html_lang' => 'es',
            'title_suffix' => 'Telaris',
            'weaving' => 'tejiendo memoria',
            'tagline_desc' => 'Un proyecto de archivo de conocimiento decolonial. Relacional, P2P, no jerárquico. Hilado por el significado.',
            'nav_home' => 'Inicio',
            'nav_documentation' => 'Documentación',
            'nav_instances' => 'Instancias',
            'nav_manifest' => 'Manifiesto',
            'nav_source_code' => 'Código fuente',
            'footer_status' => 'Sistema: En línea',
            'footer_privacy' => 'Privacidad',
            'footer_terms' => 'Términos',
            'doc_title' => 'Documentación',
            'doc_lead' => 'Documentación de Telaris, disponible como PDF descargable. Cada documento existe también en inglés, portugués y francés; usa el selector de idioma de la barra de navegación para cambiar.',
            'doc_download' => 'Descargar PDF',
            'instance_title' => 'Instancias activas',
            'instance_lead' => 'Telaris lo operan personas independientes. Cada instancia se gobierna por quien la opera y por las editoras y comunidades de origen que contribuyen a ella. A continuación, las instancias actualmente activas.',
            'manifest_title' => 'Manifiesto',
            'manifest_lead' => 'Una declaración de posición, mantenida corta a propósito. Qué es Telaris, qué rechaza, y los seis principios que lo sostienen.',
            'manifest_download_pdf' => 'Descargar como PDF',
            'privacy_title' => 'Privacidad',
            'privacy_lead' => 'Cómo Telaris maneja los datos, en www.telaris.ca y en la red de instancias independientes.',
            'privacy_download_pdf' => 'Descargar como PDF',
            'terms_title' => 'Términos de uso',
            'terms_lead' => 'Cómo se ofrece el sitio www.telaris.ca y el software de Telaris a quienes visitan, operan y editan.',
            'terms_download_pdf' => 'Descargar como PDF',
            'verify_heading_verified' => 'Correo confirmado',
            'verify_body_verified' => 'Tu solicitud para unirte queda verificada. La administración revisará la instancia y te avisará por correo cuando se publique en la Pluriverse.',
            'verify_heading_already_verified' => 'Ya estaba confirmada',
            'verify_body_already_verified' => 'Tu solicitud ya había sido verificada. Recibirás un correo cuando la administración revise la instancia.',
            'verify_heading_expired' => 'Enlace caducado',
            'verify_body_expired' => 'Este enlace de verificación caducó. Puedes enviar una nueva solicitud desde el panel de administración de tu instancia de Telaris.',
            'verify_heading_already_used' => 'Enlace ya usado',
            'verify_body_already_used' => 'Este enlace de verificación ya se usó. Si la instancia aún no está verificada, envía una nueva solicitud desde el panel de administración.',
            'verify_heading_invalid' => 'Enlace no válido',
            'verify_body_invalid' => 'Este enlace de verificación no es válido. Confirma que abriste el correo más reciente, o envía una nueva solicitud desde el panel de administración.',
            'verify_heading_missing' => 'Falta el token en la URL',
            'verify_body_missing' => 'Esta página espera un token de verificación de un solo uso. Abre el enlace desde el correo que recibiste al enviar tu solicitud.',
            'verify_heading_instance_missing' => 'Instancia no encontrada',
            'verify_body_instance_missing' => 'Tu solicitud quedó verificada, pero no se pudo ubicar la instancia asociada. Contacta a la administración si esto no era lo esperado.',
            'verify_label_name' => 'Nombre',
            'verify_label_hostname' => 'Hostname',
            'verify_label_status' => 'Estado',
            'verify_status_pending' => 'pendiente',
            'verify_status_verified' => 'verificada',
            'verify_status_published' => 'publicada',
            'verify_status_rejected' => 'rechazada',
            'verify_status_blacklisted' => 'en lista negra',
            'verify_status_outdated' => 'desactualizada',
            'verify_status_withdrawn' => 'retirada',
            'verify_status_revoked' => 'revocada',
            'verify_back_home' => 'Volver a la Pluriverse',
        ],
        'pt' => [
            'html_lang' => 'pt-BR',
            'title_suffix' => 'Telaris',
            'weaving' => 'tecendo memória',
            'tagline_desc' => 'Um projeto de arquivo de conhecimento decolonial. Relacional, P2P, não hierárquico. Fiado por significado.',
            'nav_home' => 'Início',
            'nav_documentation' => 'Documentação',
            'nav_instances' => 'Instâncias',
            'nav_manifest' => 'Manifesto',
            'nav_source_code' => 'Código fonte',
            'footer_status' => 'Sistema: Online',
            'footer_privacy' => 'Privacidade',
            'footer_terms' => 'Termos',
            'doc_title' => 'Documentação',
            'doc_lead' => 'Documentação de Telaris, disponível em PDF para download. Cada documento também existe em inglês, espanhol e francês; use o seletor de idioma na barra de navegação para alternar.',
            'doc_download' => 'Baixar PDF',
            'instance_title' => 'Instâncias ativas',
            'instance_lead' => 'Telaris é operado por pessoas independentes. Cada instância é governada por quem a opera e pelas editoras e comunidades de origem que contribuem para ela. Abaixo, as instâncias atualmente ativas.',
            'manifest_title' => 'Manifesto',
            'manifest_lead' => 'Uma declaração de posição, mantida curta de propósito. O que Telaris é, o que recusa, e os seis princípios que o sustentam.',
            'manifest_download_pdf' => 'Baixar como PDF',
            'privacy_title' => 'Privacidade',
            'privacy_lead' => 'Como Telaris lida com dados, em www.telaris.ca e na rede de instâncias independentes.',
            'privacy_download_pdf' => 'Baixar como PDF',
            'terms_title' => 'Termos de uso',
            'terms_lead' => 'Como o site www.telaris.ca e o software de Telaris são oferecidos a quem visita, opera e edita.',
            'terms_download_pdf' => 'Baixar como PDF',
            'verify_heading_verified' => 'Email confirmado',
            'verify_body_verified' => 'Sua solicitação para entrar foi verificada. A administração revisará a instância e te avisará por email quando ela for publicada na Pluriverse.',
            'verify_heading_already_verified' => 'Já estava confirmada',
            'verify_body_already_verified' => 'Sua solicitação já havia sido verificada. Você receberá um email quando a administração revisar a instância.',
            'verify_heading_expired' => 'Link expirado',
            'verify_body_expired' => 'Este link de verificação expirou. Você pode enviar uma nova solicitação pelo painel de administração da sua instância de Telaris.',
            'verify_heading_already_used' => 'Link já usado',
            'verify_body_already_used' => 'Este link de verificação já foi usado. Se a instância ainda não está verificada, envie uma nova solicitação pelo painel de administração.',
            'verify_heading_invalid' => 'Link inválido',
            'verify_body_invalid' => 'Este link de verificação não é válido. Confirme que abriu o email mais recente, ou envie uma nova solicitação pelo painel de administração.',
            'verify_heading_missing' => 'Sem token na URL',
            'verify_body_missing' => 'Esta página espera um token de verificação de uso único. Abra o link do email que você recebeu ao enviar sua solicitação.',
            'verify_heading_instance_missing' => 'Instância não encontrada',
            'verify_body_instance_missing' => 'Sua solicitação foi verificada, mas a instância associada não pôde ser localizada. Entre em contato com a administração se isto não era o esperado.',
            'verify_label_name' => 'Nome',
            'verify_label_hostname' => 'Hostname',
            'verify_label_status' => 'Estado',
            'verify_status_pending' => 'pendente',
            'verify_status_verified' => 'verificada',
            'verify_status_published' => 'publicada',
            'verify_status_rejected' => 'recusada',
            'verify_status_blacklisted' => 'em lista negra',
            'verify_status_outdated' => 'desatualizada',
            'verify_status_withdrawn' => 'retirada',
            'verify_status_revoked' => 'revogada',
            'verify_back_home' => 'Voltar à Pluriverse',
        ],
        'fr' => [
            'html_lang' => 'fr',
            'title_suffix' => 'Telaris',
            'weaving' => 'tisser la mémoire',
            'tagline_desc' => "Un projet d'archive de connaissances décoloniale. Relationnelle, P2P, non hiérarchique. Filée par le sens.",
            'nav_home' => 'Accueil',
            'nav_documentation' => 'Documentation',
            'nav_instances' => 'Instances',
            'nav_manifest' => 'Manifeste',
            'nav_source_code' => 'Code source',
            'footer_status' => 'Système : En ligne',
            'footer_privacy' => 'Confidentialité',
            'footer_terms' => 'Conditions',
            'doc_title' => 'Documentation',
            'doc_lead' => "Documentation Telaris, disponible en PDF téléchargeable. Chaque document existe aussi en anglais, espagnol et portugais ; utilise le sélecteur de langue dans la barre de navigation pour changer.",
            'doc_download' => 'Télécharger le PDF',
            'instance_title' => 'Instances actives',
            'instance_lead' => "Telaris est porté par des personnes indépendantes. Chaque instance est gouvernée par qui l'exploite et par les comptes d'édition et communautés sources qui y contribuent. Ci-dessous, les instances actuellement actives.",
            'manifest_title' => 'Manifeste',
            'manifest_lead' => "Une déclaration de position, gardée courte à dessein. Ce que Telaris est, ce qu'il refuse, et les six principes qui le tiennent ensemble.",
            'manifest_download_pdf' => 'Télécharger en PDF',
            'privacy_title' => 'Confidentialité',
            'privacy_lead' => "Comment Telaris traite les données, sur www.telaris.ca et à travers le réseau d'instances indépendantes.",
            'privacy_download_pdf' => 'Télécharger en PDF',
            'terms_title' => "Conditions d'utilisation",
            'terms_lead' => "Comment le site www.telaris.ca et le logiciel Telaris sont offerts à qui visite, exploite et édite.",
            'terms_download_pdf' => 'Télécharger en PDF',
            'verify_heading_verified' => 'Courriel confirmé',
            'verify_body_verified' => "Ta demande pour rejoindre la Pluriverse est confirmée. L'administration examinera l'instance et te préviendra par courriel lorsqu'elle sera publiée.",
            'verify_heading_already_verified' => 'Déjà confirmée',
            'verify_body_already_verified' => "Ta demande avait déjà été confirmée. Tu recevras un courriel lorsque l'administration aura examiné l'instance.",
            'verify_heading_expired' => 'Lien expiré',
            'verify_body_expired' => "Ce lien de vérification est expiré. Tu peux envoyer une nouvelle demande depuis le panneau d'administration de ton instance Telaris.",
            'verify_heading_already_used' => 'Lien déjà utilisé',
            'verify_body_already_used' => "Ce lien de vérification a déjà été utilisé. Si l'instance n'est pas encore confirmée, envoie une nouvelle demande depuis le panneau d'administration.",
            'verify_heading_invalid' => 'Lien non valide',
            'verify_body_invalid' => "Ce lien de vérification n'est pas valide. Vérifie que tu as ouvert le courriel le plus récent, ou envoie une nouvelle demande depuis le panneau d'administration.",
            'verify_heading_missing' => "Aucun jeton dans l'URL",
            'verify_body_missing' => "Cette page attend un jeton de vérification à usage unique. Ouvre le lien depuis le courriel reçu après l'envoi de ta demande.",
            'verify_heading_instance_missing' => 'Instance introuvable',
            'verify_body_instance_missing' => "Ta demande a été confirmée, mais l'instance associée n'a pas pu être trouvée. Contacte l'administration si cela n'était pas attendu.",
            'verify_label_name' => 'Nom',
            'verify_label_hostname' => 'Hôte',
            'verify_label_status' => 'Statut',
            'verify_status_pending' => 'en attente',
            'verify_status_verified' => 'confirmée',
            'verify_status_published' => 'publiée',
            'verify_status_rejected' => 'rejetée',
            'verify_status_blacklisted' => 'sur liste noire',
            'verify_status_outdated' => 'obsolète',
            'verify_status_withdrawn' => 'retirée',
            'verify_status_revoked' => 'révoquée',
            'verify_back_home' => 'Retour à la Pluriverse',
        ],
    ];
}
