<?php
declare(strict_types=1);

/**
 * Pluriverse federation schema (stage 2a) + seed helpers (stage 2f-ii onward).
 *
 * Twelve tables, ten idempotent db_ensure_* helpers (instance_status_log and
 * pluriverse_log each pair with a LIKE-copy archive table managed by the same
 * helper). All lazy at first call; reconcile forward without dumps.
 *
 * Spec: P2P federation plan v10 § Schema → Pluriverse-side (line 1144+).
 *
 * Foreign-key topology means several helpers chain into upstream ensures:
 *   - instance_status_log, anomaly_log, key_event_push_attempts → instances
 *   - key_event_push_attempts → key_events_signed
 *
 * 2f-ii adds first-admin seed helpers (db_registry_admins_count,
 * db_seed_registry_admin); these pull in inc/federation/pii.php for PII
 * encryption + lookup hashing.
 */

require_once __DIR__ . '/federation/pii.php';

/**
 * Materialize every federation table in one call. Invoked from
 * bin/setup-app.php and from CLI smoke; future federation endpoints can
 * also call this on first use to bring a fresh database to current state.
 */
function db_ensure_federation_schema(): void {
    // Shared Postgres trigger function first; the per-table ensures attach
    // BEFORE UPDATE triggers to any table carrying updated_at.
    db_ensure_pg_runtime();
    db_ensure_instances_table();
    db_ensure_instance_status_log_tables();
    db_ensure_registry_admins_table();
    db_ensure_magic_link_tokens_table();
    db_ensure_sessions_table();
    db_ensure_blacklists_table();
    db_ensure_anomaly_log_table();
    db_ensure_key_events_signed_table();
    db_ensure_key_event_push_attempts_table();
    db_ensure_pluriverse_log_tables();
    // Self-service control plane (Phase 3): public instance requests, the
    // provisioning job queue the Orrery worker drains, and operator bans.
    db_ensure_instance_requests_table();
    db_ensure_provisioning_jobs_table();
    db_ensure_operator_bans_table();
    db_ensure_pluriverse_settings_table();
}

function db_ensure_instances_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        $pdo = getDB();
        // Fresh-install shape (Postgres). ENUM columns are modelled as VARCHAR
        // with a CHECK constraint; the application layer already validates
        // these values, and VARCHAR+CHECK avoids Postgres CREATE TYPE / ALTER
        // TYPE ... ADD VALUE ceremony when the value set grows.
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS instances (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hostname VARCHAR(255) NOT NULL,
                url VARCHAR(512) NOT NULL,
                pluriverse_endpoint VARCHAR(512) NOT NULL,
                public_key BYTEA NOT NULL,
                previous_public_key BYTEA NULL,
                key_rotated_at TIMESTAMP NULL,
                rotation_reason VARCHAR(16) NULL CHECK (rotation_reason IS NULL OR rotation_reason IN ('scheduled','operational','compromise')),
                operator_email_enc BYTEA NOT NULL,
                operator_email_lookup_hash BYTEA NOT NULL,
                other_contacts_enc BYTEA NULL,
                pending_email_enc BYTEA NULL,
                pending_email_lookup_hash BYTEA NULL,
                pending_email_requested_at TIMESTAMP NULL,
                label VARCHAR(255) NOT NULL,
                editorial_framing TEXT NULL,
                publishable_slugs JSONB NULL,
                bridges JSONB NULL,
                locale CHAR(2) NOT NULL DEFAULT 'en',
                is_highlighted BOOLEAN NOT NULL DEFAULT FALSE,
                admission_status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (admission_status IN ('pending','verified','published','rejected','blacklisted','outdated','withdrawn','revoked','expired')),
                verify_by_at TIMESTAMP NULL,
                last_seen_at TIMESTAMP NULL,
                health_status VARCHAR(16) NOT NULL DEFAULT 'unknown' CHECK (health_status IN ('up','degraded','down','unknown')),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uniq_hostname UNIQUE (hostname),
                CONSTRAINT uniq_label UNIQUE (label)
            )
        ");
        // Additive column reconciliation (Postgres supports IF NOT EXISTS at
        // the column level natively). These mirror the columns that landed in
        // later releases; on a fresh install they already exist (above) and
        // these are no-ops.
        $pdo->exec("ALTER TABLE instances ADD COLUMN IF NOT EXISTS other_contacts_enc BYTEA NULL");
        $pdo->exec("ALTER TABLE instances ADD COLUMN IF NOT EXISTS locale CHAR(2) NOT NULL DEFAULT 'en'");
        $pdo->exec("ALTER TABLE instances ADD COLUMN IF NOT EXISTS pending_email_enc BYTEA NULL");
        $pdo->exec("ALTER TABLE instances ADD COLUMN IF NOT EXISTS pending_email_lookup_hash BYTEA NULL");
        $pdo->exec("ALTER TABLE instances ADD COLUMN IF NOT EXISTS pending_email_requested_at TIMESTAMP NULL");
        // Non-unique lookup indexes (2p: an operator email may run several
        // instances, so these are plain indexes, not UNIQUE). hostname + label
        // stay UNIQUE via the table constraints above.
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_operator_email_lookup ON instances (operator_email_lookup_hash)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_pending_email_lookup ON instances (pending_email_lookup_hash)");
        // BEFORE UPDATE trigger replaces MySQL's ON UPDATE CURRENT_TIMESTAMP.
        db_ensure_pg_runtime();
        db_pg_ensure_updated_at_trigger('instances');
    } catch (PDOException $e) {
        error_log('db_ensure_instances_table: ' . $e->getMessage());
    }
}

function db_ensure_instance_status_log_tables(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    db_ensure_instances_table();
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS instance_status_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instance_id INT NOT NULL,
                actor VARCHAR(255) NULL,
                action VARCHAR(64) NOT NULL,
                details_summary VARCHAR(1024) NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_instance ON instance_status_log (instance_id, created_at)");
        // FK column index (Postgres does not auto-index FK columns); the
        // composite idx_instance above leads with instance_id so it already
        // serves FK lookups. No extra index needed.
        $pdo->exec("CREATE TABLE IF NOT EXISTS instance_status_log_archive (LIKE instance_status_log INCLUDING ALL)");
    } catch (PDOException $e) {
        error_log('db_ensure_instance_status_log_tables: ' . $e->getMessage());
    }
}

function db_ensure_registry_admins_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        getDB()->exec("
            CREATE TABLE IF NOT EXISTS registry_admins (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email_enc BYTEA NOT NULL,
                email_lookup_hash BYTEA NOT NULL,
                display_name VARCHAR(255) NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                seeded_via VARCHAR(8) NOT NULL DEFAULT 'web' CHECK (seeded_via IN ('cli','web')),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uniq_email_lookup UNIQUE (email_lookup_hash)
            )
        ");
    } catch (PDOException $e) {
        error_log('db_ensure_registry_admins_table: ' . $e->getMessage());
    }
}

function db_ensure_magic_link_tokens_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS magic_link_tokens (
                token_hash BYTEA PRIMARY KEY,
                email_lookup_hash BYTEA NOT NULL,
                purpose VARCHAR(16) NOT NULL DEFAULT 'operator' CHECK (purpose IN ('operator','admin','email-change','request')),
                instance_id INT NULL,
                expires_at TIMESTAMP NOT NULL,
                consumed_at TIMESTAMP NULL
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_email_expires ON magic_link_tokens (email_lookup_hash, expires_at)");
        // Additive reconciliation for installs that predate later columns.
        $pdo->exec("ALTER TABLE magic_link_tokens ADD COLUMN IF NOT EXISTS purpose VARCHAR(16) NOT NULL DEFAULT 'operator'");
        $pdo->exec("ALTER TABLE magic_link_tokens ADD COLUMN IF NOT EXISTS instance_id INT NULL");
        // Widen the purpose CHECK to admit the Phase-3 'request' value (email
        // confirmation for a self-service instance request). The inline CHECK
        // from CREATE TABLE is named <table>_<column>_check by Postgres; drop
        // and re-add idempotently so both fresh and pre-Phase-3 installs converge.
        $pdo->exec("ALTER TABLE magic_link_tokens DROP CONSTRAINT IF EXISTS magic_link_tokens_purpose_check");
        $pdo->exec("ALTER TABLE magic_link_tokens ADD CONSTRAINT magic_link_tokens_purpose_check CHECK (purpose IN ('operator','admin','email-change','request'))");
    } catch (PDOException $e) {
        error_log('db_ensure_magic_link_tokens_table: ' . $e->getMessage());
    }
}

function db_ensure_sessions_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        $pdo = getDB();
        // last_activity_at has no BEFORE UPDATE trigger: the app sets it
        // explicitly (SET last_activity_at = NOW()) in db_validate_session,
        // which is also what the old ON UPDATE CURRENT_TIMESTAMP did.
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS sessions (
                session_id BYTEA PRIMARY KEY,
                subject_type VARCHAR(20) NOT NULL CHECK (subject_type IN ('operator','admin','operator-chooser')),
                subject_id INT NOT NULL,
                csrf_token BYTEA NULL,
                chooser_email_hash BYTEA NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP NOT NULL
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_subject ON sessions (subject_type, subject_id)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_expires ON sessions (expires_at)");
        // Additive reconciliation for installs that predate later columns.
        $pdo->exec("ALTER TABLE sessions ADD COLUMN IF NOT EXISTS csrf_token BYTEA NULL");
        $pdo->exec("ALTER TABLE sessions ADD COLUMN IF NOT EXISTS chooser_email_hash BYTEA NULL");
    } catch (PDOException $e) {
        error_log('db_ensure_sessions_table: ' . $e->getMessage());
    }
}

function db_ensure_blacklists_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        getDB()->exec("
            CREATE TABLE IF NOT EXISTS blacklists (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entry_type VARCHAR(16) NOT NULL CHECK (entry_type IN ('hostname','ip','domain')),
                entry_value VARCHAR(255) NOT NULL,
                reason TEXT NULL,
                added_by VARCHAR(255) NULL,
                added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uniq_type_value UNIQUE (entry_type, entry_value)
            )
        ");
    } catch (PDOException $e) {
        error_log('db_ensure_blacklists_table: ' . $e->getMessage());
    }
}

function db_ensure_anomaly_log_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    db_ensure_instances_table();
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS anomaly_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instance_id INT NULL,
                anomaly_type VARCHAR(64) NOT NULL,
                severity VARCHAR(8) NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','severe')),
                details_summary VARCHAR(1024) NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE SET NULL
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_severity_created ON anomaly_log (severity, created_at)");
        // FK column index (the composite above does not lead with instance_id).
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_anomaly_instance ON anomaly_log (instance_id)");
    } catch (PDOException $e) {
        error_log('db_ensure_anomaly_log_table: ' . $e->getMessage());
    }
}

function db_ensure_key_events_signed_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS key_events_signed (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                origin_host VARCHAR(255) NOT NULL,
                event_type VARCHAR(24) NOT NULL CHECK (event_type IN ('scheduled_rotation','operational_rotation','compromise','revocation')),
                occurred_at TIMESTAMP NOT NULL,
                signed_payload TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_origin_occurred ON key_events_signed (origin_host, occurred_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_created ON key_events_signed (created_at)");
    } catch (PDOException $e) {
        error_log('db_ensure_key_events_signed_table: ' . $e->getMessage());
    }
}

function db_ensure_key_event_push_attempts_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    db_ensure_key_events_signed_table();
    db_ensure_instances_table();
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS key_event_push_attempts (
                key_event_id BIGINT NOT NULL,
                instance_id INT NOT NULL,
                delivery_status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending','delivered','failed','given_up')),
                attempt_count INT NOT NULL DEFAULT 0,
                last_attempt_at TIMESTAMP NULL,
                next_attempt_at TIMESTAMP NULL,
                last_error VARCHAR(1024) NULL,
                PRIMARY KEY (key_event_id, instance_id),
                FOREIGN KEY (key_event_id) REFERENCES key_events_signed(id) ON DELETE CASCADE,
                FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_pending_next ON key_event_push_attempts (delivery_status, next_attempt_at)");
        // FK column index: key_event_id leads the PK; instance_id needs its own.
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_kepa_instance ON key_event_push_attempts (instance_id)");
    } catch (PDOException $e) {
        error_log('db_ensure_key_event_push_attempts_table: ' . $e->getMessage());
    }
}

// Creates both pluriverse_log and pluriverse_log_archive. Same shape and
// retention semantics as the instance-side table; v10 line 1327-1343.
function db_ensure_pluriverse_log_tables(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS pluriverse_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_type VARCHAR(64) NOT NULL,
                actor VARCHAR(255) NULL,
                target VARCHAR(255) NULL,
                outcome VARCHAR(8) NOT NULL CHECK (outcome IN ('success','failure','warning')),
                details_summary VARCHAR(1024) NULL,
                ip_hash BYTEA NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_event_type ON pluriverse_log (event_type, created_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_actor ON pluriverse_log (actor, created_at)");
        $pdo->exec("CREATE TABLE IF NOT EXISTS pluriverse_log_archive (LIKE pluriverse_log INCLUDING ALL)");
    } catch (PDOException $e) {
        error_log('db_ensure_pluriverse_log_tables: ' . $e->getMessage());
    }
}

// ---------------------------------------------------------------------------
// Seed helpers (stage 2f-ii onward).
// ---------------------------------------------------------------------------

/**
 * How many registry_admins rows exist. Ensures the table first so this is
 * safe to call before db_ensure_federation_schema() ran.
 */
function db_registry_admins_count(): int {
    db_ensure_registry_admins_table();
    return (int)getDB()->query("SELECT COUNT(*) FROM registry_admins")->fetchColumn();
}

/**
 * Seed a single registry_admins row with PII-encrypted email + deterministic
 * lookup hash. Idempotent at the application layer: the UNIQUE constraint on
 * email_lookup_hash means a re-seed of the same email throws (caller catches
 * if a no-op re-seed is desired).
 *
 * Row context for HKDF: hex(email_lookup_hash) — deterministic, unique per
 * row, known at insert time. Matches the v10 plan's interim stance
 * (inc/federation/pii.php docblock); aligns with the same choice that the
 * operator-application flow will use in 2f-iii.
 *
 * @param string $email        valid email; FILTER_VALIDATE_EMAIL enforced
 * @param string $displayName  1..255 chars after trim
 * @param string $seededVia    'cli' | 'web'
 * @return int                 new registry_admins.id
 * @throws InvalidArgumentException on validation failure
 * @throws PDOException on duplicate (email already an admin) or DB error
 */
function db_seed_registry_admin(string $email, string $displayName, string $seededVia = 'cli'): int {
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new InvalidArgumentException('db_seed_registry_admin: invalid email');
    }
    $displayName = trim($displayName);
    if ($displayName === '' || mb_strlen($displayName) > 255) {
        throw new InvalidArgumentException('db_seed_registry_admin: display_name must be 1..255 chars after trim');
    }
    if (!in_array($seededVia, ['cli', 'web'], true)) {
        throw new InvalidArgumentException('db_seed_registry_admin: seeded_via must be cli or web');
    }

    db_ensure_registry_admins_table();

    $lookupHash = federation_pii_lookup_hash($email);
    $rowContext = 'registry_admin:' . bin2hex($lookupHash);
    $emailEnc = federation_pii_encrypt($email, $rowContext, 'email');

    $pdo = getDB();
    // BYTEA columns travel as hex over the wire (decode at the DB) to avoid
    // Postgres rejecting a raw-binary string bind as invalid UTF-8.
    $stmt = $pdo->prepare("
        INSERT INTO registry_admins (email_enc, email_lookup_hash, display_name, seeded_via)
        VALUES (decode(:enc,'hex'), decode(:lookup,'hex'), :name, :via)
        RETURNING id
    ");
    $stmt->execute([
        ':enc' => bin2hex($emailEnc),
        ':lookup' => bin2hex($lookupHash),
        ':name' => $displayName,
        ':via' => $seededVia,
    ]);
    return (int)$stmt->fetchColumn();
}

/**
 * Row-context format for instances and registry_admins PII columns.
 *
 * info string = hex(email_lookup_hash) . ':' . column_name. Chosen because
 * the lookup hash is deterministic per email, known at INSERT time (no two
 * stage write needed), differs across rows, and survives auto-increment
 * rebuilds. Documented in inc/federation/pii.php's docblock.
 */
function federation_row_context_for_instance(string $emailLookupHash): string {
    return 'instance:' . bin2hex($emailLookupHash);
}

/**
 * Insert a pending operator application into instances. Caller has already
 * validated input and fetched the identity envelope; this helper handles
 * PII encryption, lookup-hash computation, and the INSERT itself.
 *
 * Returns the new row id.
 *
 * Encryption choices:
 * - operator_email_enc: per-row HKDF-derived key (rowContext = "instance:" .
 *   hex(lookup_hash)); column_name "email".
 * - other_contacts_enc: same rowContext, column_name "other_contacts". The
 *   plaintext is the JSON-encoded contacts array (canonical UTF-8 JSON; no
 *   pretty-printing).
 *
 * Throws PDOException on UNIQUE constraint violation (hostname or
 * operator_email_lookup_hash already present); caller should map to 409.
 */
function db_insert_instance_application(array $application, array $identity): int {
    db_ensure_instances_table();

    $email = (string)$application['operator_email'];
    $lookupHash = federation_pii_lookup_hash($email);
    $rowContext = federation_row_context_for_instance($lookupHash);

    $emailEnc = federation_pii_encrypt($email, $rowContext, 'email');

    $otherContactsEnc = null;
    if (!empty($application['other_contacts']) && is_array($application['other_contacts'])) {
        $json = json_encode(array_values($application['other_contacts']), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
        if (strlen($json) > 1024) {
            throw new InvalidArgumentException('other_contacts JSON exceeds 1024 bytes after encoding');
        }
        $otherContactsEnc = federation_pii_encrypt($json, $rowContext, 'other_contacts');
    }

    $publishableSlugs = (!empty($application['publishable_slugs']) && is_array($application['publishable_slugs']))
        ? json_encode(array_values($application['publishable_slugs']), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)
        : null;
    $bridges = (!empty($application['bridges']) && is_array($application['bridges']))
        ? json_encode(array_values($application['bridges']), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)
        : null;

    $locale = (string)($application['locale'] ?? 'en');
    if (!in_array($locale, ['en', 'es', 'pt', 'fr'], true)) {
        $locale = 'en';
    }

    $pdo = getDB();
    // BYTEA columns (public_key, *_enc, *_lookup_hash) travel as hex; the JSON
    // columns (publishable_slugs, bridges) bind as JSON text and cast to JSONB.
    $stmt = $pdo->prepare("
        INSERT INTO instances (
            hostname, url, pluriverse_endpoint, public_key,
            operator_email_enc, operator_email_lookup_hash, other_contacts_enc,
            label, editorial_framing, publishable_slugs, bridges, locale,
            admission_status, verify_by_at
        ) VALUES (
            :hostname, :url, :endpoint, decode(:pk,'hex'),
            decode(:email_enc,'hex'), decode(:lookup,'hex'), decode(:contacts,'hex'),
            :label, :framing, :slugs, :bridges, :locale,
            'pending', NOW() + INTERVAL '24 hours'
        )
        RETURNING id
    ");
    $stmt->execute([
        ':hostname' => (string)$application['hostname'],
        ':url' => (string)$application['url'],
        ':endpoint' => (string)$application['pluriverse_endpoint'],
        ':pk' => bin2hex((string)$identity['public_key']),
        ':email_enc' => bin2hex($emailEnc),
        ':lookup' => bin2hex($lookupHash),
        ':contacts' => $otherContactsEnc === null ? null : bin2hex($otherContactsEnc),
        ':label' => (string)$application['label'],
        ':framing' => isset($application['editorial_framing']) && $application['editorial_framing'] !== ''
            ? (string)$application['editorial_framing']
            : null,
        ':slugs' => $publishableSlugs,
        ':bridges' => $bridges,
        ':locale' => $locale,
    ]);
    return (int)$stmt->fetchColumn();
}

/**
 * Mint a one-hour single-use magic-link token bound to an email lookup hash.
 *
 * Persists SHA-256(raw_bytes) as token_hash; returns the raw 32 bytes so
 * the caller can base64url-encode them for the verification URL.
 *
 * The verify endpoint (2g-i) hashes the received URL parameter the same way
 * and matches against token_hash, then sets consumed_at on first success.
 */
function db_create_magic_link_token(string $emailLookupHash, int $ttlSeconds = 3600, string $purpose = 'operator', ?int $instanceId = null): string {
    if (strlen($emailLookupHash) !== 32) {
        throw new InvalidArgumentException('db_create_magic_link_token: lookup hash must be 32 bytes');
    }
    if (!in_array($purpose, ['operator', 'admin', 'email-change', 'request'], true)) {
        throw new InvalidArgumentException('db_create_magic_link_token: purpose must be operator|admin|email-change|request');
    }
    db_ensure_magic_link_tokens_table();
    $raw = random_bytes(32);
    $tokenHash = hash('sha256', $raw, true);
    // BYTEA via decode(:x,'hex'); the TTL interval is built from a bound
    // integer ($ttl * INTERVAL '1 second') since Postgres cannot bind inside
    // an interval literal.
    $stmt = getDB()->prepare("
        INSERT INTO magic_link_tokens (token_hash, email_lookup_hash, purpose, instance_id, expires_at)
        VALUES (decode(:th,'hex'), decode(:lh,'hex'), :p, :iid, NOW() + (:ttl * INTERVAL '1 second'))
    ");
    $stmt->bindValue(':th', bin2hex($tokenHash));
    $stmt->bindValue(':lh', bin2hex($emailLookupHash));
    $stmt->bindValue(':p', $purpose);
    if ($instanceId === null) {
        $stmt->bindValue(':iid', null, PDO::PARAM_NULL);
    } else {
        $stmt->bindValue(':iid', $instanceId, PDO::PARAM_INT);
    }
    $stmt->bindValue(':ttl', $ttlSeconds, PDO::PARAM_INT);
    $stmt->execute();
    return $raw;
}

/**
 * Base64url-encode raw token bytes (no padding) for use in a magic-link URL.
 */
function federation_token_url_encode(string $raw): string {
    return rtrim(strtr(base64_encode($raw), '+/', '-_'), '=');
}

/**
 * Base64url-decode a magic-link URL parameter. Returns the raw bytes or '' on
 * malformed input. The verify endpoint validates the resulting length (must
 * be 32) before using it for a hash lookup.
 */
function federation_token_url_decode(string $encoded): string {
    if ($encoded === '' || strlen($encoded) > 64) return '';
    if (!preg_match('/^[A-Za-z0-9_\-]+$/', $encoded)) return '';
    $b64 = strtr($encoded, '-_', '+/');
    $pad = strlen($b64) % 4;
    if ($pad !== 0) $b64 .= str_repeat('=', 4 - $pad);
    $raw = base64_decode($b64, true);
    return is_string($raw) ? $raw : '';
}

/**
 * Atomically consume a magic-link token by raw bytes.
 *
 * On success: marks consumed_at = NOW(), returns
 * ['status' => 'consumed', 'email_lookup_hash' => <32 bytes>].
 *
 * On a row-found-but-unusable case (expired, or already consumed), returns
 * ['status' => 'expired' | 'already_consumed', 'email_lookup_hash' => <bytes>]
 * so the caller can distinguish those from "unknown token".
 *
 * Returns null on unknown token, malformed input, or unrecoverable DB error.
 *
 * The SELECT ... FOR UPDATE + UPDATE pair runs in a transaction, so two
 * concurrent verify clicks for the same token cannot both succeed.
 */
function db_consume_magic_link_token(string $rawToken): ?array {
    if (strlen($rawToken) !== 32) return null;
    db_ensure_magic_link_tokens_table();
    $tokenHash = hash('sha256', $rawToken, true);
    $pdo = getDB();
    try {
        $pdo->beginTransaction();
        $sel = $pdo->prepare("
            SELECT encode(email_lookup_hash,'hex') AS email_lookup_hash, purpose, instance_id, expires_at, consumed_at
            FROM magic_link_tokens
            WHERE token_hash = decode(:th,'hex')
            FOR UPDATE
        ");
        $sel->bindValue(':th', bin2hex($tokenHash));
        $sel->execute();
        $row = $sel->fetch(PDO::FETCH_ASSOC);
        if ($row === false) {
            $pdo->rollBack();
            return null;
        }
        $emailLookupHash = hex2bin((string)$row['email_lookup_hash']);
        $purpose = (string)($row['purpose'] ?? 'operator');
        $instanceId = $row['instance_id'] !== null ? (int)$row['instance_id'] : null;
        if ($row['consumed_at'] !== null) {
            $pdo->rollBack();
            return ['status' => 'already_consumed', 'email_lookup_hash' => $emailLookupHash, 'purpose' => $purpose, 'instance_id' => $instanceId];
        }
        if (strtotime((string)$row['expires_at']) < time()) {
            $pdo->rollBack();
            return ['status' => 'expired', 'email_lookup_hash' => $emailLookupHash, 'purpose' => $purpose, 'instance_id' => $instanceId];
        }
        $upd = $pdo->prepare("
            UPDATE magic_link_tokens SET consumed_at = NOW()
            WHERE token_hash = decode(:th,'hex') AND consumed_at IS NULL
        ");
        $upd->bindValue(':th', bin2hex($tokenHash));
        $upd->execute();
        if ($upd->rowCount() !== 1) {
            $pdo->rollBack();
            return ['status' => 'already_consumed', 'email_lookup_hash' => $emailLookupHash, 'purpose' => $purpose, 'instance_id' => $instanceId];
        }
        $pdo->commit();
        return ['status' => 'consumed', 'email_lookup_hash' => $emailLookupHash, 'purpose' => $purpose, 'instance_id' => $instanceId];
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        error_log('db_consume_magic_link_token: ' . $e->getMessage());
        return null;
    }
}

/**
 * Fetch the instance row keyed by operator_email_lookup_hash (the same 32-byte
 * value `magic_link_tokens.email_lookup_hash` carries).
 *
 * Returns the row as an associative array, or null if no such instance.
 * The returned shape includes locale + admission_status; PII columns are
 * NOT returned (verify never needs the plaintext email).
 */
function db_get_instance_by_email_lookup_hash(string $lookupHash): ?array {
    if (strlen($lookupHash) !== 32) return null;
    db_ensure_instances_table();
    $stmt = getDB()->prepare("
        SELECT id, hostname, url, label, locale, admission_status
        FROM instances
        WHERE operator_email_lookup_hash = decode(:lh,'hex')
        LIMIT 1
    ");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : $row;
}

/**
 * All instances operated by one email lookup hash (2p: an operator may run
 * several). Optionally restrict to session-eligible statuses so the chooser
 * never lists an instance the operator can't actually sign in to.
 *
 * @return list<array{id:int,hostname:string,url:string,label:string,locale:string,admission_status:string}>
 */
function db_get_instances_by_email_lookup_hash(string $lookupHash, bool $sessionEligibleOnly = true): array {
    if (strlen($lookupHash) !== 32) return [];
    db_ensure_instances_table();
    $sql = "SELECT id, hostname, url, label, locale, admission_status
            FROM instances
            WHERE operator_email_lookup_hash = decode(:lh,'hex')";
    if ($sessionEligibleOnly) {
        $sql .= " AND admission_status IN ('verified','published','outdated','withdrawn')";
    }
    $sql .= " ORDER BY label ASC";
    $stmt = getDB()->prepare($sql);
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    $out = [];
    foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $r) {
        $out[] = [
            'id' => (int)$r['id'],
            'hostname' => (string)$r['hostname'],
            'url' => (string)$r['url'],
            'label' => (string)$r['label'],
            'locale' => (string)$r['locale'],
            'admission_status' => (string)$r['admission_status'],
        ];
    }
    return $out;
}

/**
 * Transition `instances.admission_status` from $expected → $next, atomically.
 *
 * Returns true iff a row was updated (i.e. the instance was in $expected at
 * the moment of the UPDATE). Returns false if the instance is in some other
 * state (idempotent: a second verify click on an already-verified instance
 * returns false without changing anything).
 *
 * Also appends to instance_status_log so the admin surface can replay
 * lifecycle events. The log write happens in the same transaction as the
 * status flip so they cannot diverge.
 */
function db_transition_instance_admission(
    int $instanceId,
    string $expected,
    string $next,
    string $actor,
    ?string $details = null
): bool {
    db_ensure_instances_table();
    db_ensure_instance_status_log_tables();
    $pdo = getDB();
    try {
        $pdo->beginTransaction();
        $upd = $pdo->prepare("
            UPDATE instances SET admission_status = :next
            WHERE id = :id AND admission_status = :expected
        ");
        $upd->execute([
            ':next' => $next,
            ':expected' => $expected,
            ':id' => $instanceId,
        ]);
        if ($upd->rowCount() !== 1) {
            $pdo->rollBack();
            return false;
        }
        $log = $pdo->prepare("
            INSERT INTO instance_status_log (instance_id, actor, action, details_summary)
            VALUES (:id, :actor, :action, :details)
        ");
        $log->execute([
            ':id' => $instanceId,
            ':actor' => $actor,
            ':action' => 'transition:' . $expected . '->' . $next,
            ':details' => $details,
        ]);
        $pdo->commit();
        return true;
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        error_log('db_transition_instance_admission: ' . $e->getMessage());
        return false;
    }
}

/**
 * Check whether an instance Name (DB column `label`) is available.
 *
 * Single indexed lookup against the UNIQUE uniq_label index. Returns true
 * if no instance currently claims this label. Case-insensitive via the
 * table collation (utf8mb4_unicode_ci).
 *
 * Used by the apply-form's async availability check and by the pre-INSERT
 * conflict probe in apply_handler.php.
 */
function db_label_available(string $label): bool {
    db_ensure_instances_table();
    $label = trim($label);
    if ($label === '' || mb_strlen($label) > 255) {
        return false;
    }
    $stmt = getDB()->prepare("SELECT 1 FROM instances WHERE label = :l LIMIT 1");
    $stmt->execute([':l' => $label]);
    return $stmt->fetchColumn() === false;
}

/**
 * Mint a session for the given subject. Returns the raw 32-byte session ID;
 * the page layer wraps it in a base64url cookie payload.
 *
 * subject_type='operator' uses instances.id; subject_type='admin' uses
 * registry_admins.id. The sessions table indexes both with (subject_type,
 * subject_id) so lookups stay O(log n) when both surfaces coexist.
 */
function db_create_session(string $subjectType, int $subjectId, int $ttlSeconds = 1209600): string {
    if (!in_array($subjectType, ['operator', 'admin'], true)) {
        throw new InvalidArgumentException('db_create_session: subject_type must be operator|admin');
    }
    if ($subjectId <= 0) {
        throw new InvalidArgumentException('db_create_session: subject_id must be positive');
    }
    db_ensure_sessions_table();
    $raw = random_bytes(32);
    $csrf = random_bytes(32);
    $stmt = getDB()->prepare("
        INSERT INTO sessions (session_id, subject_type, subject_id, csrf_token, expires_at)
        VALUES (decode(:sid,'hex'), :st, :si, decode(:csrf,'hex'), NOW() + (:ttl * INTERVAL '1 second'))
    ");
    $stmt->bindValue(':sid', bin2hex($raw));
    $stmt->bindValue(':st', $subjectType);
    $stmt->bindValue(':si', $subjectId, PDO::PARAM_INT);
    $stmt->bindValue(':csrf', bin2hex($csrf));
    $stmt->bindValue(':ttl', $ttlSeconds, PDO::PARAM_INT);
    $stmt->execute();
    return $raw;
}

/**
 * Mint a short-lived 'operator-chooser' session (2p). Used when a magic-link
 * sign-in resolves to an email running multiple instances: the operator has
 * proven control of the email but not yet picked which instance to manage.
 * subject_id is 0 (unbound); the email hash rides in chooser_email_hash. The
 * dashboard renders the picker and calls db_bind_chooser_session on pick.
 *
 * Short TTL (15 min default) because it's a transient pre-pick state.
 */
function db_create_chooser_session(string $emailLookupHash, int $ttlSeconds = 900): string {
    if (strlen($emailLookupHash) !== 32) {
        throw new InvalidArgumentException('db_create_chooser_session: email lookup hash must be 32 bytes');
    }
    db_ensure_sessions_table();
    $raw = random_bytes(32);
    $csrf = random_bytes(32);
    $stmt = getDB()->prepare("
        INSERT INTO sessions (session_id, subject_type, subject_id, csrf_token, chooser_email_hash, expires_at)
        VALUES (decode(:sid,'hex'), 'operator-chooser', 0, decode(:csrf,'hex'), decode(:ceh,'hex'), NOW() + (:ttl * INTERVAL '1 second'))
    ");
    $stmt->bindValue(':sid', bin2hex($raw));
    $stmt->bindValue(':csrf', bin2hex($csrf));
    $stmt->bindValue(':ceh', bin2hex($emailLookupHash));
    $stmt->bindValue(':ttl', $ttlSeconds, PDO::PARAM_INT);
    $stmt->execute();
    return $raw;
}

/**
 * Bind an 'operator-chooser' session to a chosen instance (2p). Upgrades the
 * row in place to a normal operator session: subject_type -> 'operator',
 * subject_id -> $instanceId, chooser_email_hash cleared, expiry extended to
 * the standard operator TTL. The instance MUST belong to the session's
 * chooser_email_hash (verified by the caller) before this is called.
 *
 * Returns true on a successful bind (the row was an operator-chooser session
 * for this session_id), false otherwise.
 */
function db_bind_chooser_session(string $rawSessionId, int $instanceId, int $ttlSeconds = 1209600): bool {
    if (strlen($rawSessionId) !== 32 || $instanceId <= 0) return false;
    db_ensure_sessions_table();
    $stmt = getDB()->prepare("
        UPDATE sessions
        SET subject_type = 'operator', subject_id = :iid, chooser_email_hash = NULL,
            expires_at = NOW() + (:ttl * INTERVAL '1 second')
        WHERE session_id = decode(:sid,'hex') AND subject_type = 'operator-chooser'
    ");
    $stmt->bindValue(':iid', $instanceId, PDO::PARAM_INT);
    $stmt->bindValue(':ttl', $ttlSeconds, PDO::PARAM_INT);
    $stmt->bindValue(':sid', bin2hex($rawSessionId));
    $stmt->execute();
    return $stmt->rowCount() === 1;
}

/**
 * Validate a raw session ID against the sessions table.
 *
 * Returns ['subject_type' => 'operator'|'admin', 'subject_id' => int] on a
 * live (not expired) session, or null otherwise. Touches last_activity_at
 * on a hit so the sliding-TTL semantics work without a separate write.
 *
 * Returning null is the sole "this cookie is no good" signal; the caller
 * clears the cookie when it sees null. We don't distinguish expired vs
 * unknown deliberately (no cookie fishing).
 */
function db_validate_session(string $rawSessionId): ?array {
    if (strlen($rawSessionId) !== 32) return null;
    db_ensure_sessions_table();
    $pdo = getDB();
    $stmt = $pdo->prepare("
        SELECT subject_type, subject_id,
               encode(csrf_token,'hex') AS csrf_token,
               encode(chooser_email_hash,'hex') AS chooser_email_hash
        FROM sessions
        WHERE session_id = decode(:sid,'hex') AND expires_at > NOW()
        LIMIT 1
    ");
    $stmt->bindValue(':sid', bin2hex($rawSessionId));
    $stmt->execute();
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($row === false) return null;
    // BYTEA columns came back hex-encoded; decode to raw bytes (NULL stays
    // NULL) so callers see the same shape as the MySQL build.
    $row['csrf_token'] = $row['csrf_token'] !== null ? hex2bin((string)$row['csrf_token']) : null;
    $row['chooser_email_hash'] = $row['chooser_email_hash'] !== null ? hex2bin((string)$row['chooser_email_hash']) : null;
    // Pre-2g-ii sessions might have NULL csrf_token. Lazy-mint on first
    // use so existing sessions keep working without a forced re-login.
    if ($row['csrf_token'] === null) {
        $csrf = random_bytes(32);
        $upd = $pdo->prepare("UPDATE sessions SET csrf_token = decode(:c,'hex') WHERE session_id = decode(:sid,'hex')");
        $upd->bindValue(':c', bin2hex($csrf));
        $upd->bindValue(':sid', bin2hex($rawSessionId));
        $upd->execute();
        $row['csrf_token'] = $csrf;
    }
    // Touch last_activity_at explicitly (replaces the old ON UPDATE
    // CURRENT_TIMESTAMP column clause).
    $upd = $pdo->prepare("UPDATE sessions SET last_activity_at = NOW() WHERE session_id = decode(:sid,'hex')");
    $upd->bindValue(':sid', bin2hex($rawSessionId));
    $upd->execute();
    return $row;
}

/**
 * Fetch the instance row by primary key, including encrypted PII columns.
 *
 * Used by the dashboard to render the operator's own instance. The caller
 * is responsible for decrypting `operator_email_enc` / `other_contacts_enc`
 * via federation_pii_decrypt with the right rowContext.
 */
/**
 * Mark any pending instance whose verify_by_at deadline has passed as
 * expired, and log the transition. Returns the count of rows transitioned.
 *
 * Lazy sweep: called from the apply handler (so a fresh apply attempt sees
 * stale-pending rows as expired and can replace them) and from the
 * dashboard sign-in POST (so /dashboard reflects expiry on the next user
 * visit). A proper cron job is deferred until the federation is busy
 * enough that the lazy path stops covering hygiene.
 */
function db_expire_stale_pending_instances(): int {
    db_ensure_instances_table();
    db_ensure_instance_status_log_tables();
    $pdo = getDB();
    try {
        $pdo->beginTransaction();
        $stmt = $pdo->prepare("
            SELECT id FROM instances
            WHERE admission_status = 'pending' AND verify_by_at IS NOT NULL AND verify_by_at < NOW()
            FOR UPDATE
        ");
        $stmt->execute();
        $ids = array_map('intval', $stmt->fetchAll(PDO::FETCH_COLUMN));
        if ($ids === []) {
            $pdo->commit();
            return 0;
        }
        $place = implode(',', array_fill(0, count($ids), '?'));
        $pdo->prepare("UPDATE instances SET admission_status = 'expired' WHERE id IN ($place)")->execute($ids);
        $logStmt = $pdo->prepare("
            INSERT INTO instance_status_log (instance_id, actor, action, details_summary)
            VALUES (:id, 'system', 'transition:pending->expired', '24h verification window passed without confirmation')
        ");
        foreach ($ids as $id) {
            $logStmt->execute([':id' => $id]);
        }
        $pdo->commit();
        return count($ids);
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        error_log('db_expire_stale_pending_instances: ' . $e->getMessage());
        return 0;
    }
}

/**
 * Delete an instance row and its cascading log entries. Used when a fresh
 * apply replaces an expired prior attempt. Returns true iff a row was
 * deleted.
 *
 * Caller is responsible for verifying the row's admission_status before
 * calling: this function does not check, it just removes. Wrong calls
 * would lose data.
 */
function db_delete_instance(int $instanceId): bool {
    db_ensure_instances_table();
    $stmt = getDB()->prepare("DELETE FROM instances WHERE id = :id");
    $stmt->execute([':id' => $instanceId]);
    return $stmt->rowCount() === 1;
}

/**
 * Fetch an active admin row by operator_email_lookup_hash (used to gate
 * /admin sign-in: only emails on the registry_admins roster can mint an
 * admin session). Inactive admins (is_active = FALSE) are excluded so
 * deactivating an admin immediately blocks further sign-ins.
 */
function db_get_admin_by_email_lookup_hash(string $lookupHash): ?array {
    if (strlen($lookupHash) !== 32) return null;
    db_ensure_registry_admins_table();
    $stmt = getDB()->prepare("
        SELECT id, display_name, is_active
        FROM registry_admins
        WHERE email_lookup_hash = decode(:lh,'hex') AND is_active = TRUE
        LIMIT 1
    ");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : $row;
}

/**
 * Fetch an admin row by primary key. Used when an admin session resolves
 * (subject_type = 'admin', subject_id = id) to render the admin landing.
 */
function db_get_admin_by_id(int $id): ?array {
    db_ensure_registry_admins_table();
    $stmt = getDB()->prepare("SELECT id, display_name, is_active, created_at FROM registry_admins WHERE id = :id LIMIT 1");
    $stmt->execute([':id' => $id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : $row;
}

/**
 * Column list for `instances` SELECT * replacements. BYTEA columns are
 * hex-encoded over the wire (encode(col,'hex') AS col); decode them with
 * federation_instance_decode_binary() before use.
 */
function federation_instance_select_columns(): string {
    return "id, hostname, url, pluriverse_endpoint,
            encode(public_key,'hex') AS public_key,
            encode(previous_public_key,'hex') AS previous_public_key,
            key_rotated_at, rotation_reason,
            encode(operator_email_enc,'hex') AS operator_email_enc,
            encode(operator_email_lookup_hash,'hex') AS operator_email_lookup_hash,
            encode(other_contacts_enc,'hex') AS other_contacts_enc,
            encode(pending_email_enc,'hex') AS pending_email_enc,
            encode(pending_email_lookup_hash,'hex') AS pending_email_lookup_hash,
            pending_email_requested_at,
            label, editorial_framing, publishable_slugs, bridges, locale,
            is_highlighted, admission_status, verify_by_at, last_seen_at,
            health_status, created_at, updated_at";
}

/**
 * Decode the hex-encoded BYTEA columns on an `instances` row back to raw
 * bytes (NULLs preserved), so callers see the same shape as the MySQL build.
 */
function federation_instance_decode_binary(array $row): array {
    foreach ([
        'public_key', 'previous_public_key', 'operator_email_enc',
        'operator_email_lookup_hash', 'other_contacts_enc',
        'pending_email_enc', 'pending_email_lookup_hash',
    ] as $c) {
        if (array_key_exists($c, $row)) {
            $row[$c] = ($row[$c] !== null && $row[$c] !== '') ? hex2bin((string)$row[$c]) : ($row[$c] === '' ? '' : null);
        }
    }
    return $row;
}

function db_get_instance_by_id(int $instanceId): ?array {
    db_ensure_instances_table();
    $stmt = getDB()->prepare("SELECT " . federation_instance_select_columns() . " FROM instances WHERE id = :id LIMIT 1");
    $stmt->execute([':id' => $instanceId]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : federation_instance_decode_binary($row);
}

/**
 * Find an instance row whose pending_email_lookup_hash matches. Used by the
 * verify handler to dispatch purpose='email-change' magic-link consumes
 * (the token's lookup hash is the NEW email's hash; the canonical
 * operator_email_lookup_hash still points at the OLD email until promotion).
 */
function db_get_instance_by_pending_email_lookup_hash(string $hash): ?array {
    if (strlen($hash) !== 32) return null;
    db_ensure_instances_table();
    $stmt = getDB()->prepare("SELECT " . federation_instance_select_columns() . " FROM instances WHERE pending_email_lookup_hash = decode(:h,'hex') LIMIT 1");
    $stmt->bindValue(':h', bin2hex($hash));
    $stmt->execute();
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : federation_instance_decode_binary($row);
}

/**
 * Atomically promote a pending email change to canonical. Decrypts the
 * pending email under the OLD row context, re-encrypts the email and any
 * other PII (other_contacts) under the NEW row context (derived from the
 * new email's lookup hash), updates the canonical columns, and clears the
 * pending_* columns. Logs the change with actor='operator'.
 *
 * Returns true on success. On any error (PII decrypt failure, write
 * conflict, etc.) rolls back and returns false.
 */
function db_promote_email_change(int $instanceId): bool {
    db_ensure_instances_table();
    db_ensure_instance_status_log_tables();
    require_once __DIR__ . '/federation/pii.php';
    $pdo = getDB();
    try {
        $pdo->beginTransaction();
        $sel = $pdo->prepare("
            SELECT encode(operator_email_enc,'hex') AS operator_email_enc,
                   encode(operator_email_lookup_hash,'hex') AS operator_email_lookup_hash,
                   encode(other_contacts_enc,'hex') AS other_contacts_enc,
                   encode(pending_email_enc,'hex') AS pending_email_enc,
                   encode(pending_email_lookup_hash,'hex') AS pending_email_lookup_hash
            FROM instances WHERE id = :id FOR UPDATE
        ");
        $sel->execute([':id' => $instanceId]);
        $row = $sel->fetch(PDO::FETCH_ASSOC);
        if ($row === false
            || empty($row['pending_email_enc'])
            || empty($row['pending_email_lookup_hash'])
        ) {
            $pdo->rollBack();
            return false;
        }
        // Decode hex BYTEA back to raw bytes for the PII helpers.
        $row = federation_instance_decode_binary($row);
        $oldContext = federation_row_context_for_instance((string)$row['operator_email_lookup_hash']);
        $newContext = federation_row_context_for_instance((string)$row['pending_email_lookup_hash']);

        // Decrypt the pending email under OLD context + 'pending_email' info.
        $newEmail = federation_pii_decrypt((string)$row['pending_email_enc'], $oldContext, 'pending_email');

        // Re-encrypt under NEW context + 'email' info (canonical column name).
        $newEmailEnc = federation_pii_encrypt($newEmail, $newContext, 'email');

        // Re-encrypt other_contacts under NEW context (its row context also
        // changed because it's tied to the operator_email_lookup_hash).
        $newOtherEnc = null;
        if (!empty($row['other_contacts_enc'])) {
            $contactsJson = federation_pii_decrypt((string)$row['other_contacts_enc'], $oldContext, 'other_contacts');
            $newOtherEnc = federation_pii_encrypt($contactsJson, $newContext, 'other_contacts');
        }

        $upd = $pdo->prepare("
            UPDATE instances
            SET operator_email_enc = decode(:email_enc,'hex'),
                operator_email_lookup_hash = decode(:lookup,'hex'),
                other_contacts_enc = decode(:other_enc,'hex'),
                pending_email_enc = NULL,
                pending_email_lookup_hash = NULL,
                pending_email_requested_at = NULL
            WHERE id = :id
        ");
        $upd->bindValue(':email_enc', bin2hex($newEmailEnc));
        $upd->bindValue(':lookup', bin2hex((string)$row['pending_email_lookup_hash']));
        if ($newOtherEnc !== null) {
            $upd->bindValue(':other_enc', bin2hex($newOtherEnc));
        } else {
            $upd->bindValue(':other_enc', null, PDO::PARAM_NULL);
        }
        $upd->bindValue(':id', $instanceId, PDO::PARAM_INT);
        $upd->execute();

        $log = $pdo->prepare("
            INSERT INTO instance_status_log (instance_id, actor, action, details_summary)
            VALUES (:id, 'operator', 'edit', 'operator email changed via dashboard (magic-link confirmed)')
        ");
        $log->execute([':id' => $instanceId]);

        $pdo->commit();
        return true;
    } catch (Throwable $e) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        error_log('db_promote_email_change: ' . $e->getMessage());
        return false;
    }
}

/**
 * Fetch the most recent status-log entries for an instance, newest first.
 */
function db_get_instance_status_log(int $instanceId, int $limit = 25): array {
    db_ensure_instance_status_log_tables();
    $limit = max(1, min(200, $limit));
    $stmt = getDB()->prepare("
        SELECT action, actor, details_summary, created_at
        FROM instance_status_log
        WHERE instance_id = :id
        ORDER BY id DESC
        LIMIT {$limit}
    ");
    $stmt->execute([':id' => $instanceId]);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * Destroy a session by raw ID. Returns true iff a row was deleted.
 *
 * Called on logout (when 2g-ii ships) and when a session is invalidated
 * for some other reason (operator revoked, etc.).
 */
function db_destroy_session(string $rawSessionId): bool {
    if (strlen($rawSessionId) !== 32) return false;
    db_ensure_sessions_table();
    $stmt = getDB()->prepare("DELETE FROM sessions WHERE session_id = decode(:sid,'hex')");
    $stmt->bindValue(':sid', bin2hex($rawSessionId));
    $stmt->execute();
    return $stmt->rowCount() === 1;
}

// ===========================================================================
// Self-service control plane (Phase 3)
// ===========================================================================
//
// Three tables model the self-service instance lifecycle:
//
//   instance_requests  - a public, double-opt-in request to provision a
//                        Telaris instance. Distinct from `instances` (the
//                        federation member registry): a request is the intake
//                        artefact; an `instances` row is only created at
//                        provision time (3f auto-trust). Operator name + email
//                        are encrypted at rest exactly like the instances PII.
//   provisioning_jobs  - the typed job queue the Orrery worker drains. The
//                        web app (www-data) only ever INSERTs a job; the worker
//                        (a separate Orrery user) claims it FOR UPDATE SKIP
//                        LOCKED, re-validates, and runs the fixed provisioner
//                        sequence. Shape mirrors key_event_push_attempts.
//   operator_bans      - a super-admin ban keyed by operator email lookup hash,
//                        outliving any single request so a banned operator
//                        cannot simply resubmit.
//
// Request lifecycle:
//   pending_confirmation --(email link)--> confirmed --(admin approve)--> approved
//      |                                       |                            |
//      |                                       +--(admin reject)--> rejected
//      |                                                                    |
//      +--(admin/abuse)--> banned                          (worker) provisioning
//                                                                    |       |
//                                                            provisioned   failed

/**
 * Row-context for instance_requests PII columns (operator_email_enc,
 * operator_name_enc). Mirrors federation_row_context_for_instance but with a
 * distinct prefix so a request and its eventual instance never share a derived
 * key. column_name is 'email' or 'name'.
 */
function federation_row_context_for_request(string $emailLookupHash): string {
    return 'instance_request:' . bin2hex($emailLookupHash);
}

function db_ensure_instance_requests_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    db_ensure_instances_table();
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS instance_requests (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                label VARCHAR(63) NOT NULL,
                site_name VARCHAR(255) NOT NULL,
                site_tagline VARCHAR(512) NULL,
                editorial_framing TEXT NULL,
                locale CHAR(2) NOT NULL DEFAULT 'en',
                federate BOOLEAN NOT NULL DEFAULT TRUE,
                operator_name_enc BYTEA NULL,
                operator_email_enc BYTEA NOT NULL,
                operator_email_lookup_hash BYTEA NOT NULL,
                request_ip_hash BYTEA NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'pending_confirmation'
                    CHECK (status IN ('pending_confirmation','confirmed','approved','provisioning','provisioned','rejected','failed','banned')),
                confirmed_at TIMESTAMP NULL,
                reviewed_at TIMESTAMP NULL,
                reviewed_by VARCHAR(255) NULL,
                decision_reason TEXT NULL,
                instance_id INT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE SET NULL
            )
        ");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ir_operator_lookup ON instance_requests (operator_email_lookup_hash)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ir_status ON instance_requests (status, created_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ir_label ON instance_requests (label)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_ir_instance ON instance_requests (instance_id)");
        db_ensure_pg_runtime();
        db_pg_ensure_updated_at_trigger('instance_requests');
    } catch (PDOException $e) {
        error_log('db_ensure_instance_requests_table: ' . $e->getMessage());
    }
}

function db_ensure_provisioning_jobs_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    db_ensure_instance_requests_table();
    try {
        $pdo = getDB();
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS provisioning_jobs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                request_id INT NULL,
                job_type VARCHAR(16) NOT NULL DEFAULT 'provision'
                    CHECK (job_type IN ('provision','deprovision','suspend','resume')),
                label VARCHAR(63) NOT NULL,
                payload JSONB NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued','running','done','failed','given_up')),
                attempt_count INT NOT NULL DEFAULT 0,
                last_attempt_at TIMESTAMP NULL,
                next_attempt_at TIMESTAMP NULL,
                last_error VARCHAR(2048) NULL,
                result JSONB NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (request_id) REFERENCES instance_requests(id) ON DELETE SET NULL
            )
        ");
        // The worker claims with: status='queued' AND next_attempt_at due,
        // ordered by id, FOR UPDATE SKIP LOCKED. This index serves that claim.
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_pj_claim ON provisioning_jobs (status, next_attempt_at)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_pj_request ON provisioning_jobs (request_id)");
        db_ensure_pg_runtime();
        db_pg_ensure_updated_at_trigger('provisioning_jobs');
    } catch (PDOException $e) {
        error_log('db_ensure_provisioning_jobs_table: ' . $e->getMessage());
    }
}

function db_ensure_operator_bans_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        getDB()->exec("
            CREATE TABLE IF NOT EXISTS operator_bans (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                operator_email_lookup_hash BYTEA NOT NULL,
                reason TEXT NULL,
                banned_by VARCHAR(255) NULL,
                banned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uniq_ban_lookup UNIQUE (operator_email_lookup_hash)
            )
        ");
    } catch (PDOException $e) {
        error_log('db_ensure_operator_bans_table: ' . $e->getMessage());
    }
}

/**
 * Lightweight audit-log writer. The codebase has only inline pluriverse_log
 * INSERTs (relay_handler etc.); the self-service surface logs from several
 * call sites, so one best-effort helper avoids repeating the boilerplate.
 * Never throws (audit logging must not break the action it records).
 */
function pluriverse_log_event(string $eventType, string $outcome, ?string $actor = null, ?string $target = null, ?string $summary = null): void {
    if (!in_array($outcome, ['success', 'failure', 'warning'], true)) {
        $outcome = 'warning';
    }
    try {
        db_ensure_pluriverse_log_tables();
        $stmt = getDB()->prepare("
            INSERT INTO pluriverse_log (event_type, actor, target, outcome, details_summary)
            VALUES (:e, :a, :t, :o, :d)
        ");
        $stmt->execute([
            ':e' => substr($eventType, 0, 64),
            ':a' => $actor !== null ? substr($actor, 0, 255) : null,
            ':t' => $target !== null ? substr($target, 0, 255) : null,
            ':o' => $outcome,
            ':d' => $summary !== null ? substr($summary, 0, 1024) : null,
        ]);
    } catch (Throwable $e) {
        error_log('pluriverse_log_event: ' . $e->getMessage());
    }
}

/**
 * Insert a public instance request in 'pending_confirmation'. Encrypts the
 * operator email + name at rest (per-row HKDF key, request row-context) and
 * stores a deterministic lookup hash of the email for cap/ban/confirm lookups.
 * The request IP, when supplied, is stored only as a keyed hash for abuse
 * correlation (never plaintext).
 *
 * $req keys: label, site_name, site_tagline?, editorial_framing?, locale?,
 *            federate?(bool, default true), operator_name?, operator_email,
 *            request_ip?
 *
 * Returns the new request id.
 */
function db_insert_instance_request(array $req): int {
    db_ensure_instance_requests_table();

    $email = trim((string)($req['operator_email'] ?? ''));
    if ($email === '') {
        throw new InvalidArgumentException('db_insert_instance_request: operator_email required');
    }
    $lookupHash = federation_pii_lookup_hash($email);
    $rowContext = federation_row_context_for_request($lookupHash);
    $emailEnc = federation_pii_encrypt($email, $rowContext, 'email');

    $nameEnc = null;
    $name = trim((string)($req['operator_name'] ?? ''));
    if ($name !== '') {
        $nameEnc = federation_pii_encrypt($name, $rowContext, 'name');
    }

    $ipHash = null;
    $ip = trim((string)($req['request_ip'] ?? ''));
    if ($ip !== '') {
        $ipHash = federation_pii_lookup_hash($ip);
    }

    $locale = (string)($req['locale'] ?? 'en');
    if (!in_array($locale, ['en', 'es', 'pt', 'fr'], true)) {
        $locale = 'en';
    }
    $federate = array_key_exists('federate', $req) ? (bool)$req['federate'] : true;

    $stmt = getDB()->prepare("
        INSERT INTO instance_requests (
            label, site_name, site_tagline, editorial_framing, locale, federate,
            operator_name_enc, operator_email_enc, operator_email_lookup_hash, request_ip_hash
        ) VALUES (
            :label, :site_name, :tagline, :framing, :locale, :federate,
            decode(:name_enc,'hex'), decode(:email_enc,'hex'), decode(:lookup,'hex'), decode(:ip_hash,'hex')
        )
        RETURNING id
    ");
    $stmt->bindValue(':label', (string)$req['label']);
    $stmt->bindValue(':site_name', (string)$req['site_name']);
    $stmt->bindValue(':tagline', isset($req['site_tagline']) && $req['site_tagline'] !== '' ? (string)$req['site_tagline'] : null);
    $stmt->bindValue(':framing', isset($req['editorial_framing']) && $req['editorial_framing'] !== '' ? (string)$req['editorial_framing'] : null);
    $stmt->bindValue(':locale', $locale);
    $stmt->bindValue(':federate', $federate, PDO::PARAM_BOOL);
    // decode(NULL,'hex') is NULL, so nullable BYTEA columns bind cleanly here.
    $stmt->bindValue(':name_enc', $nameEnc === null ? null : bin2hex($nameEnc));
    $stmt->bindValue(':email_enc', bin2hex($emailEnc));
    $stmt->bindValue(':lookup', bin2hex($lookupHash));
    $stmt->bindValue(':ip_hash', $ipHash === null ? null : bin2hex($ipHash));
    $stmt->execute();
    return (int)$stmt->fetchColumn();
}

/**
 * Fetch one request by id. With $withPii, also decrypts and adds
 * 'operator_email' + 'operator_name' (admin display); without it, PII stays
 * sealed. BYTEA columns come back as hex via encode().
 */
function db_get_instance_request_by_id(int $id, bool $withPii = false): ?array {
    db_ensure_instance_requests_table();
    $stmt = getDB()->prepare("
        SELECT id, label, site_name, site_tagline, editorial_framing, locale, federate,
               encode(operator_name_enc,'hex') AS operator_name_enc,
               encode(operator_email_enc,'hex') AS operator_email_enc,
               encode(operator_email_lookup_hash,'hex') AS operator_email_lookup_hash,
               status, confirmed_at, reviewed_at, reviewed_by, decision_reason,
               instance_id, created_at, updated_at
        FROM instance_requests WHERE id = :id
    ");
    $stmt->execute([':id' => $id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($row === false) return null;
    if ($withPii) {
        $lookupHash = hex2bin((string)$row['operator_email_lookup_hash']);
        $rowContext = federation_row_context_for_request($lookupHash);
        try {
            $row['operator_email'] = federation_pii_decrypt(hex2bin((string)$row['operator_email_enc']), $rowContext, 'email');
        } catch (Throwable $e) {
            $row['operator_email'] = null;
        }
        $row['operator_name'] = null;
        if ($row['operator_name_enc'] !== null && $row['operator_name_enc'] !== '') {
            try {
                $row['operator_name'] = federation_pii_decrypt(hex2bin((string)$row['operator_name_enc']), $rowContext, 'name');
            } catch (Throwable $e) {
                $row['operator_name'] = null;
            }
        }
    }
    return $row;
}

/**
 * The latest request for an operator (by email lookup hash) in a given set of
 * statuses, newest first. Used by the confirm endpoint (purpose='request'
 * tokens carry the request id in instance_id, but the lookup hash is the
 * authoritative key the token also binds).
 */
function db_get_latest_request_by_lookup_hash(string $lookupHash, array $statuses): ?array {
    if (strlen($lookupHash) !== 32 || $statuses === []) return null;
    db_ensure_instance_requests_table();
    $place = implode(',', array_fill(0, count($statuses), '?'));
    $stmt = getDB()->prepare("
        SELECT id, label, status FROM instance_requests
        WHERE operator_email_lookup_hash = decode(?,'hex') AND status IN ($place)
        ORDER BY id DESC LIMIT 1
    ");
    $stmt->execute(array_merge([bin2hex($lookupHash)], $statuses));
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : $row;
}

/**
 * Count an operator's requests that occupy a slot toward their cap: anything
 * not in a terminal-negative state (rejected/failed/banned). Used by the
 * per-operator cap gate (3c/3e).
 */
function db_count_active_requests_by_lookup_hash(string $lookupHash): int {
    if (strlen($lookupHash) !== 32) return 0;
    db_ensure_instance_requests_table();
    $stmt = getDB()->prepare("
        SELECT COUNT(*) FROM instance_requests
        WHERE operator_email_lookup_hash = decode(:lh,'hex')
          AND status NOT IN ('rejected','failed','banned')
    ");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    return (int)$stmt->fetchColumn();
}

/** True if the label is taken by a live request or an existing instance. */
function db_label_in_use(string $label): bool {
    db_ensure_instance_requests_table();
    $pdo = getDB();
    $a = $pdo->prepare("SELECT 1 FROM instances WHERE label = :l LIMIT 1");
    $a->execute([':l' => $label]);
    if ($a->fetchColumn() !== false) return true;
    $b = $pdo->prepare("
        SELECT 1 FROM instance_requests
        WHERE label = :l AND status NOT IN ('rejected','failed','banned') LIMIT 1
    ");
    $b->execute([':l' => $label]);
    return $b->fetchColumn() !== false;
}

/**
 * Atomic request status transition: flips status only if currently $expected
 * (idempotent), optionally setting confirmed_at / review fields / instance_id,
 * and writes a pluriverse_log row. Returns true iff a row changed.
 *
 * $extra may set: 'confirmed_at'(bool), 'reviewed_by'(string), 'reason'(string),
 *                 'instance_id'(int).
 */
function db_transition_instance_request(int $id, string $expected, string $next, string $actor, array $extra = []): bool {
    db_ensure_instance_requests_table();
    $sets = ['status = :next'];
    $params = [':next' => $next, ':id' => $id, ':expected' => $expected];
    if (!empty($extra['confirmed_at'])) {
        $sets[] = 'confirmed_at = NOW()';
    }
    if (in_array($next, ['approved', 'rejected'], true)) {
        $sets[] = 'reviewed_at = NOW()';
        $sets[] = 'reviewed_by = :rb';
        $params[':rb'] = isset($extra['reviewed_by']) ? substr((string)$extra['reviewed_by'], 0, 255) : $actor;
    }
    if (array_key_exists('reason', $extra)) {
        $sets[] = 'decision_reason = :reason';
        $params[':reason'] = $extra['reason'] !== null ? (string)$extra['reason'] : null;
    }
    if (array_key_exists('instance_id', $extra)) {
        $sets[] = 'instance_id = :iid';
        $params[':iid'] = $extra['instance_id'] !== null ? (int)$extra['instance_id'] : null;
    }
    $sql = 'UPDATE instance_requests SET ' . implode(', ', $sets) . ' WHERE id = :id AND status = :expected';
    $stmt = getDB()->prepare($sql);
    $stmt->execute($params);
    $changed = $stmt->rowCount() === 1;
    if ($changed) {
        pluriverse_log_event(
            'instance_request_' . $next,
            'success',
            $actor,
            'request#' . $id,
            'status ' . $expected . ' -> ' . $next . (isset($extra['reason']) && $extra['reason'] !== null ? ' (' . substr((string)$extra['reason'], 0, 200) . ')' : '')
        );
    }
    return $changed;
}

/** True if this operator (by email lookup hash) is banned. */
function db_operator_is_banned(string $lookupHash): bool {
    if (strlen($lookupHash) !== 32) return false;
    db_ensure_operator_bans_table();
    $stmt = getDB()->prepare("SELECT 1 FROM operator_bans WHERE operator_email_lookup_hash = decode(:lh,'hex') LIMIT 1");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    return $stmt->fetchColumn() !== false;
}

/** Ban an operator by email lookup hash (idempotent: updates reason on repeat). */
function db_add_operator_ban(string $lookupHash, ?string $reason, string $bannedBy): void {
    if (strlen($lookupHash) !== 32) {
        throw new InvalidArgumentException('db_add_operator_ban: lookup hash must be 32 bytes');
    }
    db_ensure_operator_bans_table();
    $stmt = getDB()->prepare("
        INSERT INTO operator_bans (operator_email_lookup_hash, reason, banned_by)
        VALUES (decode(:lh,'hex'), :reason, :by)
        ON CONFLICT (operator_email_lookup_hash)
        DO UPDATE SET reason = EXCLUDED.reason, banned_by = EXCLUDED.banned_by, banned_at = NOW()
    ");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->bindValue(':reason', $reason !== null && $reason !== '' ? $reason : null);
    $stmt->bindValue(':by', substr($bannedBy, 0, 255));
    $stmt->execute();
    pluriverse_log_event('operator_ban', 'success', $bannedBy, null, 'banned operator (lookup ' . substr(bin2hex($lookupHash), 0, 16) . '...)');
}

/** Lift an operator ban. Returns true iff a ban row was removed. */
function db_remove_operator_ban(string $lookupHash, string $actor): bool {
    if (strlen($lookupHash) !== 32) return false;
    db_ensure_operator_bans_table();
    $stmt = getDB()->prepare("DELETE FROM operator_bans WHERE operator_email_lookup_hash = decode(:lh,'hex')");
    $stmt->bindValue(':lh', bin2hex($lookupHash));
    $stmt->execute();
    $removed = $stmt->rowCount() >= 1;
    if ($removed) {
        pluriverse_log_event('operator_unban', 'success', $actor, null, 'unbanned operator (lookup ' . substr(bin2hex($lookupHash), 0, 16) . '...)');
    }
    return $removed;
}

/**
 * Enqueue a typed provisioning job. The web app calls this (after super-admin
 * approval, or for an admin-initiated suspend/resume/deprovision); the Orrery
 * worker drains it out of band. $payload is the validated, NON-secret job
 * parameters plus the sealed operator handoff blob (3b); it must be JSON-safe.
 *
 * Returns the new job id.
 */
function db_enqueue_provisioning_job(?int $requestId, string $jobType, string $label, array $payload): int {
    if (!in_array($jobType, ['provision', 'deprovision', 'suspend', 'resume'], true)) {
        throw new InvalidArgumentException('db_enqueue_provisioning_job: bad job_type');
    }
    db_ensure_provisioning_jobs_table();
    $json = json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    $stmt = getDB()->prepare("
        INSERT INTO provisioning_jobs (request_id, job_type, label, payload, status, next_attempt_at)
        VALUES (:rid, :jt, :label, CAST(:payload AS JSONB), 'queued', NOW())
        RETURNING id
    ");
    $stmt->bindValue(':rid', $requestId, $requestId === null ? PDO::PARAM_NULL : PDO::PARAM_INT);
    $stmt->bindValue(':jt', $jobType);
    $stmt->bindValue(':label', $label);
    $stmt->bindValue(':payload', $json);
    $stmt->execute();
    $jobId = (int)$stmt->fetchColumn();
    pluriverse_log_event('provisioning_job_enqueued', 'success', null, $label, $jobType . ' job#' . $jobId . ($requestId !== null ? ' request#' . $requestId : ''));
    return $jobId;
}

/** Fetch one job by id (for tests + the admin job view). payload/result as text. */
function db_get_provisioning_job_by_id(int $id): ?array {
    db_ensure_provisioning_jobs_table();
    $stmt = getDB()->prepare("
        SELECT id, request_id, job_type, label, payload::text AS payload, status,
               attempt_count, last_attempt_at, next_attempt_at, last_error,
               result::text AS result, created_at, updated_at
        FROM provisioning_jobs WHERE id = :id
    ");
    $stmt->execute([':id' => $id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row === false ? null : $row;
}

// ---------------------------------------------------------------------------
// Pluriverse operational settings (small key-value store).
//
// The Pluriverse is a single instance, so a simple settings table is enough
// (no idempotent-migration ceremony beyond the ensure). Used for the
// self-service control-plane knobs (open/closed, per-operator cap); the
// super-admin flips these in the admin view (3e).
// ---------------------------------------------------------------------------

function db_ensure_pluriverse_settings_table(): void {
    static $checked = false;
    if ($checked) return;
    $checked = true;
    try {
        getDB()->exec("
            CREATE TABLE IF NOT EXISTS pluriverse_settings (
                key VARCHAR(64) PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ");
    } catch (PDOException $e) {
        error_log('db_ensure_pluriverse_settings_table: ' . $e->getMessage());
    }
}

function pluriverse_setting_get(string $key, string $default = ''): string {
    db_ensure_pluriverse_settings_table();
    $stmt = getDB()->prepare("SELECT value FROM pluriverse_settings WHERE key = :k");
    $stmt->execute([':k' => $key]);
    $v = $stmt->fetchColumn();
    return $v === false ? $default : (string)$v;
}

function pluriverse_setting_set(string $key, string $value): void {
    db_ensure_pluriverse_settings_table();
    $stmt = getDB()->prepare("
        INSERT INTO pluriverse_settings (key, value) VALUES (:k, :v)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
    ");
    $stmt->execute([':k' => $key, ':v' => $value]);
}

/** Is the public self-service request form accepting requests? Default: closed. */
function db_self_service_is_open(): bool {
    return pluriverse_setting_get('self_service_open', '0') === '1';
}

/** Max active (non-terminal) requests one operator email may hold. Default: 3. */
function db_self_service_operator_cap(): int {
    return max(1, (int)pluriverse_setting_get('self_service_operator_cap', '3'));
}

/**
 * Seal a small operator-identity blob for a provisioning job payload, so the
 * Orrery worker (a different user that CANNOT read the Pluriverse PII master
 * key) can recover the operator email/name without any plaintext PII living in
 * the job at rest. Mirrors the worker's handoff_unseal() exactly:
 * libsodium secretbox, returns hex(nonce(24) || cipher). The key is shared only
 * between www-data and the Orrery user at HANDOFF_KEY_FILE (0640).
 *
 * Throws RuntimeException if the shared key is missing/short (so an approve
 * fails loudly rather than enqueueing an unprovisionable job).
 */
function pluriverse_orrery_handoff_seal(array $data): string {
    $path = defined('TELARIS_ORRERY_HANDOFF_KEY') ? (string)TELARIS_ORRERY_HANDOFF_KEY : '/etc/telaris-orrery/handoff.key';
    if (!is_readable($path)) {
        throw new RuntimeException('Orrery handoff key not readable: ' . $path);
    }
    $raw = trim((string)file_get_contents($path));
    if (strlen($raw) === 64 && ctype_xdigit($raw)) {
        $raw = (string)hex2bin($raw);
    }
    if (strlen($raw) !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES) {
        throw new RuntimeException('Orrery handoff key must be 32 bytes (or 64 hex).');
    }
    $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
    $plain = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    $cipher = sodium_crypto_secretbox($plain, $nonce, $raw);
    sodium_memzero($raw);
    return bin2hex($nonce . $cipher);
}

/**
 * Approve a confirmed request: seal the operator handoff, enqueue a provision
 * job, and flip the request confirmed -> approved (atomic on the status guard).
 * Returns the job id, or null if the request was not in 'confirmed' (e.g. a
 * double click). The Orrery worker then drains the job and provisions.
 */
function db_approve_instance_request(int $requestId, string $actor): ?int {
    $req = db_get_instance_request_by_id($requestId, true);
    if ($req === null || (string)$req['status'] !== 'confirmed') {
        return null;
    }
    $sealed = pluriverse_orrery_handoff_seal([
        'email' => (string)($req['operator_email'] ?? ''),
        'first' => (string)($req['operator_name'] ?? ''),
        'last'  => '',
    ]);
    $payload = [
        'site_name'    => (string)$req['site_name'],
        'site_tagline' => $req['site_tagline'] !== null ? (string)$req['site_tagline'] : '',
        'locale'       => (string)$req['locale'],
        'federate'     => (bool)$req['federate'],
        'operator_sealed' => $sealed,
    ];
    // Flip status first (atomic guard) so a double click cannot enqueue twice;
    // only enqueue if we won the transition.
    if (!db_transition_instance_request($requestId, 'confirmed', 'approved', $actor)) {
        return null;
    }
    return db_enqueue_provisioning_job($requestId, 'provision', (string)$req['label'], $payload);
}

/**
 * Requests in the given statuses, newest first, with operator email/name
 * decrypted for display. The admin view calls this twice: once for the
 * review queue (pre-decision statuses) and once for the Orrery instances
 * list (post-approval lifecycle), so a provisioned instance leaves the
 * review queue.
 *
 * @param list<string> $statuses
 * @return list<array<string,mixed>>
 */
function db_list_requests_by_status(array $statuses, int $limit = 200): array {
    if ($statuses === []) return [];
    db_ensure_instance_requests_table();
    $limit = max(1, min(500, $limit));
    $place = implode(',', array_fill(0, count($statuses), '?'));
    $stmt = getDB()->prepare("SELECT id FROM instance_requests WHERE status IN ($place) ORDER BY id DESC LIMIT {$limit}");
    $stmt->execute($statuses);
    $out = [];
    foreach ($stmt->fetchAll(PDO::FETCH_COLUMN) as $id) {
        $row = db_get_instance_request_by_id((int)$id, true);
        if ($row !== null) $out[] = $row;
    }
    return $out;
}

/** Recent provisioning jobs for the admin job panel. */
function db_list_recent_provisioning_jobs(int $limit = 20): array {
    db_ensure_provisioning_jobs_table();
    $limit = max(1, min(200, $limit));
    return getDB()->query("
        SELECT id, request_id, job_type, label, status, attempt_count, last_error, updated_at
        FROM provisioning_jobs ORDER BY id DESC LIMIT {$limit}
    ")->fetchAll(PDO::FETCH_ASSOC);
}
